// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: karlo/business/v1/business.proto

package businessv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusinessService_GetOrder_FullMethodName                  = "/karlo.business.v1.BusinessService/GetOrder"
	BusinessService_ListOrders_FullMethodName                = "/karlo.business.v1.BusinessService/ListOrders"
	BusinessService_GetOrderSummary_FullMethodName           = "/karlo.business.v1.BusinessService/GetOrderSummary"
	BusinessService_GetAgreement_FullMethodName              = "/karlo.business.v1.BusinessService/GetAgreement"
	BusinessService_GetInvoice_FullMethodName                = "/karlo.business.v1.BusinessService/GetInvoice"
	BusinessService_GetActiveShipmentByDriver_FullMethodName = "/karlo.business.v1.BusinessService/GetActiveShipmentByDriver"
	BusinessService_ReportGeofenceEvent_FullMethodName       = "/karlo.business.v1.BusinessService/ReportGeofenceEvent"
)

// BusinessServiceClient is the client API for BusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BusinessService owns the transactional core: agreements, orders, the shipment
// lifecycle and invoices. It is the only service that writes to those tables.
//
// The RPCs here are deliberately narrow. Most business interaction happens over
// this service's own REST API, which the front ends call. gRPC exists for what
// OTHER services need to ask, which is mostly read-side: the notification
// service resolving a subject for a deep link, the accounting service (already
// separate) pulling invoices, the telemetry service (already separate)
// correlating a GPS fix with an active shipment.
type BusinessServiceClient interface {
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	// GetOrderSummary returns the small projection other services need to render
	// a reference to an order without pulling the whole aggregate.
	GetOrderSummary(ctx context.Context, in *GetOrderSummaryRequest, opts ...grpc.CallOption) (*GetOrderSummaryResponse, error)
	GetAgreement(ctx context.Context, in *GetAgreementRequest, opts ...grpc.CallOption) (*GetAgreementResponse, error)
	GetInvoice(ctx context.Context, in *GetInvoiceRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error)
	// GetActiveShipmentByDriver tells the telemetry service which shipment a
	// driver's position updates belong to.
	GetActiveShipmentByDriver(ctx context.Context, in *GetActiveShipmentByDriverRequest, opts ...grpc.CallOption) (*GetActiveShipmentByDriverResponse, error)
	// ReportGeofenceEvent is the inbound edge from telemetry: it reports that a
	// tracked truck entered or left a warehouse geofence, which can advance the
	// shipment state machine when the company has finish-with-geofencing on.
	ReportGeofenceEvent(ctx context.Context, in *ReportGeofenceEventRequest, opts ...grpc.CallOption) (*ReportGeofenceEventResponse, error)
}

type businessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessServiceClient(cc grpc.ClientConnInterface) BusinessServiceClient {
	return &businessServiceClient{cc}
}

func (c *businessServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, BusinessService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, BusinessService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetOrderSummary(ctx context.Context, in *GetOrderSummaryRequest, opts ...grpc.CallOption) (*GetOrderSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderSummaryResponse)
	err := c.cc.Invoke(ctx, BusinessService_GetOrderSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetAgreement(ctx context.Context, in *GetAgreementRequest, opts ...grpc.CallOption) (*GetAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgreementResponse)
	err := c.cc.Invoke(ctx, BusinessService_GetAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetInvoice(ctx context.Context, in *GetInvoiceRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvoiceResponse)
	err := c.cc.Invoke(ctx, BusinessService_GetInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) GetActiveShipmentByDriver(ctx context.Context, in *GetActiveShipmentByDriverRequest, opts ...grpc.CallOption) (*GetActiveShipmentByDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveShipmentByDriverResponse)
	err := c.cc.Invoke(ctx, BusinessService_GetActiveShipmentByDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) ReportGeofenceEvent(ctx context.Context, in *ReportGeofenceEventRequest, opts ...grpc.CallOption) (*ReportGeofenceEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportGeofenceEventResponse)
	err := c.cc.Invoke(ctx, BusinessService_ReportGeofenceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServiceServer is the server API for BusinessService service.
// All implementations must embed UnimplementedBusinessServiceServer
// for forward compatibility.
//
// BusinessService owns the transactional core: agreements, orders, the shipment
// lifecycle and invoices. It is the only service that writes to those tables.
//
// The RPCs here are deliberately narrow. Most business interaction happens over
// this service's own REST API, which the front ends call. gRPC exists for what
// OTHER services need to ask, which is mostly read-side: the notification
// service resolving a subject for a deep link, the accounting service (already
// separate) pulling invoices, the telemetry service (already separate)
// correlating a GPS fix with an active shipment.
type BusinessServiceServer interface {
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	// GetOrderSummary returns the small projection other services need to render
	// a reference to an order without pulling the whole aggregate.
	GetOrderSummary(context.Context, *GetOrderSummaryRequest) (*GetOrderSummaryResponse, error)
	GetAgreement(context.Context, *GetAgreementRequest) (*GetAgreementResponse, error)
	GetInvoice(context.Context, *GetInvoiceRequest) (*GetInvoiceResponse, error)
	// GetActiveShipmentByDriver tells the telemetry service which shipment a
	// driver's position updates belong to.
	GetActiveShipmentByDriver(context.Context, *GetActiveShipmentByDriverRequest) (*GetActiveShipmentByDriverResponse, error)
	// ReportGeofenceEvent is the inbound edge from telemetry: it reports that a
	// tracked truck entered or left a warehouse geofence, which can advance the
	// shipment state machine when the company has finish-with-geofencing on.
	ReportGeofenceEvent(context.Context, *ReportGeofenceEventRequest) (*ReportGeofenceEventResponse, error)
	mustEmbedUnimplementedBusinessServiceServer()
}

// UnimplementedBusinessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusinessServiceServer struct{}

func (UnimplementedBusinessServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedBusinessServiceServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedBusinessServiceServer) GetOrderSummary(context.Context, *GetOrderSummaryRequest) (*GetOrderSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderSummary not implemented")
}
func (UnimplementedBusinessServiceServer) GetAgreement(context.Context, *GetAgreementRequest) (*GetAgreementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgreement not implemented")
}
func (UnimplementedBusinessServiceServer) GetInvoice(context.Context, *GetInvoiceRequest) (*GetInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvoice not implemented")
}
func (UnimplementedBusinessServiceServer) GetActiveShipmentByDriver(context.Context, *GetActiveShipmentByDriverRequest) (*GetActiveShipmentByDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveShipmentByDriver not implemented")
}
func (UnimplementedBusinessServiceServer) ReportGeofenceEvent(context.Context, *ReportGeofenceEventRequest) (*ReportGeofenceEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportGeofenceEvent not implemented")
}
func (UnimplementedBusinessServiceServer) mustEmbedUnimplementedBusinessServiceServer() {}
func (UnimplementedBusinessServiceServer) testEmbeddedByValue()                         {}

// UnsafeBusinessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessServiceServer will
// result in compilation errors.
type UnsafeBusinessServiceServer interface {
	mustEmbedUnimplementedBusinessServiceServer()
}

func RegisterBusinessServiceServer(s grpc.ServiceRegistrar, srv BusinessServiceServer) {
	// If the following call panics, it indicates UnimplementedBusinessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusinessService_ServiceDesc, srv)
}

func _BusinessService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetOrderSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetOrderSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_GetOrderSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetOrderSummary(ctx, req.(*GetOrderSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_GetAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetAgreement(ctx, req.(*GetAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_GetInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetInvoice(ctx, req.(*GetInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_GetActiveShipmentByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveShipmentByDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).GetActiveShipmentByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_GetActiveShipmentByDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).GetActiveShipmentByDriver(ctx, req.(*GetActiveShipmentByDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_ReportGeofenceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportGeofenceEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).ReportGeofenceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_ReportGeofenceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).ReportGeofenceEvent(ctx, req.(*ReportGeofenceEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessService_ServiceDesc is the grpc.ServiceDesc for BusinessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "karlo.business.v1.BusinessService",
	HandlerType: (*BusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _BusinessService_GetOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _BusinessService_ListOrders_Handler,
		},
		{
			MethodName: "GetOrderSummary",
			Handler:    _BusinessService_GetOrderSummary_Handler,
		},
		{
			MethodName: "GetAgreement",
			Handler:    _BusinessService_GetAgreement_Handler,
		},
		{
			MethodName: "GetInvoice",
			Handler:    _BusinessService_GetInvoice_Handler,
		},
		{
			MethodName: "GetActiveShipmentByDriver",
			Handler:    _BusinessService_GetActiveShipmentByDriver_Handler,
		},
		{
			MethodName: "ReportGeofenceEvent",
			Handler:    _BusinessService_ReportGeofenceEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "karlo/business/v1/business.proto",
}
