// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: karlo/business/v1/business.proto

package businessv1

import (
	v1 "github.com/karlo/notification-service/internal/platform/genproto/karlo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeofenceTransition int32

const (
	GeofenceTransition_GEOFENCE_TRANSITION_UNSPECIFIED GeofenceTransition = 0
	GeofenceTransition_GEOFENCE_TRANSITION_ENTER       GeofenceTransition = 1
	GeofenceTransition_GEOFENCE_TRANSITION_EXIT        GeofenceTransition = 2
)

// Enum value maps for GeofenceTransition.
var (
	GeofenceTransition_name = map[int32]string{
		0: "GEOFENCE_TRANSITION_UNSPECIFIED",
		1: "GEOFENCE_TRANSITION_ENTER",
		2: "GEOFENCE_TRANSITION_EXIT",
	}
	GeofenceTransition_value = map[string]int32{
		"GEOFENCE_TRANSITION_UNSPECIFIED": 0,
		"GEOFENCE_TRANSITION_ENTER":       1,
		"GEOFENCE_TRANSITION_EXIT":        2,
	}
)

func (x GeofenceTransition) Enum() *GeofenceTransition {
	p := new(GeofenceTransition)
	*p = x
	return p
}

func (x GeofenceTransition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeofenceTransition) Descriptor() protoreflect.EnumDescriptor {
	return file_karlo_business_v1_business_proto_enumTypes[0].Descriptor()
}

func (GeofenceTransition) Type() protoreflect.EnumType {
	return &file_karlo_business_v1_business_proto_enumTypes[0]
}

func (x GeofenceTransition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeofenceTransition.Descriptor instead.
func (GeofenceTransition) EnumDescriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber            string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	AgreementId            string                 `protobuf:"bytes,3,opt,name=agreement_id,json=agreementId,proto3" json:"agreement_id,omitempty"`
	ShipperCompanyId       string                 `protobuf:"bytes,4,opt,name=shipper_company_id,json=shipperCompanyId,proto3" json:"shipper_company_id,omitempty"`
	TransporterCompanyId   string                 `protobuf:"bytes,5,opt,name=transporter_company_id,json=transporterCompanyId,proto3" json:"transporter_company_id,omitempty"`
	DriverId               string                 `protobuf:"bytes,6,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TruckId                string                 `protobuf:"bytes,7,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	OriginWarehouseId      string                 `protobuf:"bytes,8,opt,name=origin_warehouse_id,json=originWarehouseId,proto3" json:"origin_warehouse_id,omitempty"`
	DestinationWarehouseId string                 `protobuf:"bytes,9,opt,name=destination_warehouse_id,json=destinationWarehouseId,proto3" json:"destination_warehouse_id,omitempty"`
	StatusCode             string                 `protobuf:"bytes,10,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Status                 string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	StatusAlias            string                 `protobuf:"bytes,12,opt,name=status_alias,json=statusAlias,proto3" json:"status_alias,omitempty"`
	PickupAt               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=pickup_at,json=pickupAt,proto3" json:"pickup_at,omitempty"`
	DeliveryAt             *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=delivery_at,json=deliveryAt,proto3" json:"delivery_at,omitempty"`
	Price                  float64                `protobuf:"fixed64,15,opt,name=price,proto3" json:"price,omitempty"`
	CurrencyId             string                 `protobuf:"bytes,16,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	ParentOrderId          string                 `protobuf:"bytes,17,opt,name=parent_order_id,json=parentOrderId,proto3" json:"parent_order_id,omitempty"`
	Deleted                bool                   `protobuf:"varint,18,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Detail                 *structpb.Struct       `protobuf:"bytes,19,opt,name=detail,proto3" json:"detail,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *Order) GetAgreementId() string {
	if x != nil {
		return x.AgreementId
	}
	return ""
}

func (x *Order) GetShipperCompanyId() string {
	if x != nil {
		return x.ShipperCompanyId
	}
	return ""
}

func (x *Order) GetTransporterCompanyId() string {
	if x != nil {
		return x.TransporterCompanyId
	}
	return ""
}

func (x *Order) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Order) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

func (x *Order) GetOriginWarehouseId() string {
	if x != nil {
		return x.OriginWarehouseId
	}
	return ""
}

func (x *Order) GetDestinationWarehouseId() string {
	if x != nil {
		return x.DestinationWarehouseId
	}
	return ""
}

func (x *Order) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetStatusAlias() string {
	if x != nil {
		return x.StatusAlias
	}
	return ""
}

func (x *Order) GetPickupAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupAt
	}
	return nil
}

func (x *Order) GetDeliveryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryAt
	}
	return nil
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *Order) GetParentOrderId() string {
	if x != nil {
		return x.ParentOrderId
	}
	return ""
}

func (x *Order) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Order) GetDetail() *structpb.Struct {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// OrderSummary is the cross-service projection of an order.
type OrderSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber          string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	StatusCode           string                 `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ShipperCompanyId     string                 `protobuf:"bytes,5,opt,name=shipper_company_id,json=shipperCompanyId,proto3" json:"shipper_company_id,omitempty"`
	TransporterCompanyId string                 `protobuf:"bytes,6,opt,name=transporter_company_id,json=transporterCompanyId,proto3" json:"transporter_company_id,omitempty"`
	DriverId             string                 `protobuf:"bytes,7,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrderSummary) Reset() {
	*x = OrderSummary{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSummary) ProtoMessage() {}

func (x *OrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSummary.ProtoReflect.Descriptor instead.
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{1}
}

func (x *OrderSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderSummary) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *OrderSummary) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *OrderSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderSummary) GetShipperCompanyId() string {
	if x != nil {
		return x.ShipperCompanyId
	}
	return ""
}

func (x *OrderSummary) GetTransporterCompanyId() string {
	if x != nil {
		return x.TransporterCompanyId
	}
	return ""
}

func (x *OrderSummary) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// company_id scopes the listing. Required: there is no unscoped order list.
	CompanyId     string    `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Query         *v1.Query `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListOrdersRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetOrderSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderSummaryRequest) Reset() {
	*x = GetOrderSummaryRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderSummaryRequest) ProtoMessage() {}

func (x *GetOrderSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderSummaryRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderSummaryRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetOrderSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*OrderSummary        `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderSummaryResponse) Reset() {
	*x = GetOrderSummaryResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderSummaryResponse) ProtoMessage() {}

func (x *GetOrderSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetOrderSummaryResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderSummaryResponse) GetSummaries() []*OrderSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type Agreement struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgreementNumber      string                 `protobuf:"bytes,2,opt,name=agreement_number,json=agreementNumber,proto3" json:"agreement_number,omitempty"`
	ShipperCompanyId     string                 `protobuf:"bytes,3,opt,name=shipper_company_id,json=shipperCompanyId,proto3" json:"shipper_company_id,omitempty"`
	TransporterCompanyId string                 `protobuf:"bytes,4,opt,name=transporter_company_id,json=transporterCompanyId,proto3" json:"transporter_company_id,omitempty"`
	StatusCode           string                 `protobuf:"bytes,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Status               string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ValidFrom            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Verified             bool                   `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"`
	Detail               *structpb.Struct       `protobuf:"bytes,10,opt,name=detail,proto3" json:"detail,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Agreement) Reset() {
	*x = Agreement{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agreement) ProtoMessage() {}

func (x *Agreement) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agreement.ProtoReflect.Descriptor instead.
func (*Agreement) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{8}
}

func (x *Agreement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agreement) GetAgreementNumber() string {
	if x != nil {
		return x.AgreementNumber
	}
	return ""
}

func (x *Agreement) GetShipperCompanyId() string {
	if x != nil {
		return x.ShipperCompanyId
	}
	return ""
}

func (x *Agreement) GetTransporterCompanyId() string {
	if x != nil {
		return x.TransporterCompanyId
	}
	return ""
}

func (x *Agreement) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Agreement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agreement) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Agreement) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *Agreement) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Agreement) GetDetail() *structpb.Struct {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Agreement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgreementRequest) Reset() {
	*x = GetAgreementRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgreementRequest) ProtoMessage() {}

func (x *GetAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgreementRequest.ProtoReflect.Descriptor instead.
func (*GetAgreementRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgreementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agreement     *Agreement             `protobuf:"bytes,1,opt,name=agreement,proto3" json:"agreement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgreementResponse) Reset() {
	*x = GetAgreementResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgreementResponse) ProtoMessage() {}

func (x *GetAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgreementResponse.ProtoReflect.Descriptor instead.
func (*GetAgreementResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{10}
}

func (x *GetAgreementResponse) GetAgreement() *Agreement {
	if x != nil {
		return x.Agreement
	}
	return nil
}

type Invoice struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNumber        string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	OrderId              string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShipperCompanyId     string                 `protobuf:"bytes,4,opt,name=shipper_company_id,json=shipperCompanyId,proto3" json:"shipper_company_id,omitempty"`
	TransporterCompanyId string                 `protobuf:"bytes,5,opt,name=transporter_company_id,json=transporterCompanyId,proto3" json:"transporter_company_id,omitempty"`
	StatusCode           string                 `protobuf:"bytes,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Subtotal             float64                `protobuf:"fixed64,7,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Ppn                  float64                `protobuf:"fixed64,8,opt,name=ppn,proto3" json:"ppn,omitempty"`
	Pph23                float64                `protobuf:"fixed64,9,opt,name=pph23,proto3" json:"pph23,omitempty"`
	Total                float64                `protobuf:"fixed64,10,opt,name=total,proto3" json:"total,omitempty"`
	CurrencyId           string                 `protobuf:"bytes,11,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	IssuedAt             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	PaidAt               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{11}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *Invoice) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Invoice) GetShipperCompanyId() string {
	if x != nil {
		return x.ShipperCompanyId
	}
	return ""
}

func (x *Invoice) GetTransporterCompanyId() string {
	if x != nil {
		return x.TransporterCompanyId
	}
	return ""
}

func (x *Invoice) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Invoice) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Invoice) GetPpn() float64 {
	if x != nil {
		return x.Ppn
	}
	return 0
}

func (x *Invoice) GetPph23() float64 {
	if x != nil {
		return x.Pph23
	}
	return 0
}

func (x *Invoice) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Invoice) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *Invoice) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Invoice) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{12}
}

func (x *GetInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{13}
}

func (x *GetInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type Shipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TruckId       string                 `protobuf:"bytes,4,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	StatusCode    string                 `protobuf:"bytes,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{14}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Shipment) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Shipment) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

func (x *Shipment) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Shipment) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Shipment) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type GetActiveShipmentByDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveShipmentByDriverRequest) Reset() {
	*x = GetActiveShipmentByDriverRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveShipmentByDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveShipmentByDriverRequest) ProtoMessage() {}

func (x *GetActiveShipmentByDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveShipmentByDriverRequest.ProtoReflect.Descriptor instead.
func (*GetActiveShipmentByDriverRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{15}
}

func (x *GetActiveShipmentByDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetActiveShipmentByDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveShipmentByDriverResponse) Reset() {
	*x = GetActiveShipmentByDriverResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveShipmentByDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveShipmentByDriverResponse) ProtoMessage() {}

func (x *GetActiveShipmentByDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveShipmentByDriverResponse.ProtoReflect.Descriptor instead.
func (*GetActiveShipmentByDriverResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{16}
}

func (x *GetActiveShipmentByDriverResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *GetActiveShipmentByDriverResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ReportGeofenceEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Transition    GeofenceTransition     `protobuf:"varint,3,opt,name=transition,proto3,enum=karlo.business.v1.GeofenceTransition" json:"transition,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGeofenceEventRequest) Reset() {
	*x = ReportGeofenceEventRequest{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGeofenceEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGeofenceEventRequest) ProtoMessage() {}

func (x *ReportGeofenceEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGeofenceEventRequest.ProtoReflect.Descriptor instead.
func (*ReportGeofenceEventRequest) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{17}
}

func (x *ReportGeofenceEventRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ReportGeofenceEventRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *ReportGeofenceEventRequest) GetTransition() GeofenceTransition {
	if x != nil {
		return x.Transition
	}
	return GeofenceTransition_GEOFENCE_TRANSITION_UNSPECIFIED
}

func (x *ReportGeofenceEventRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ReportGeofenceEventRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ReportGeofenceEventRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ReportGeofenceEventResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// new_status_code is set when the event advanced the shipment state machine.
	NewStatusCode string `protobuf:"bytes,2,opt,name=new_status_code,json=newStatusCode,proto3" json:"new_status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGeofenceEventResponse) Reset() {
	*x = ReportGeofenceEventResponse{}
	mi := &file_karlo_business_v1_business_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGeofenceEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGeofenceEventResponse) ProtoMessage() {}

func (x *ReportGeofenceEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_business_v1_business_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGeofenceEventResponse.ProtoReflect.Descriptor instead.
func (*ReportGeofenceEventResponse) Descriptor() ([]byte, []int) {
	return file_karlo_business_v1_business_proto_rawDescGZIP(), []int{18}
}

func (x *ReportGeofenceEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportGeofenceEventResponse) GetNewStatusCode() string {
	if x != nil {
		return x.NewStatusCode
	}
	return ""
}

var File_karlo_business_v1_business_proto protoreflect.FileDescriptor

const file_karlo_business_v1_business_proto_rawDesc = "" +
	"\n" +
	" karlo/business/v1/business.proto\x12\x11karlo.business.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ckarlo/common/v1/common.proto\"\xd5\x06\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12!\n" +
	"\fagreement_id\x18\x03 \x01(\tR\vagreementId\x12,\n" +
	"\x12shipper_company_id\x18\x04 \x01(\tR\x10shipperCompanyId\x124\n" +
	"\x16transporter_company_id\x18\x05 \x01(\tR\x14transporterCompanyId\x12\x1b\n" +
	"\tdriver_id\x18\x06 \x01(\tR\bdriverId\x12\x19\n" +
	"\btruck_id\x18\a \x01(\tR\atruckId\x12.\n" +
	"\x13origin_warehouse_id\x18\b \x01(\tR\x11originWarehouseId\x128\n" +
	"\x18destination_warehouse_id\x18\t \x01(\tR\x16destinationWarehouseId\x12\x1f\n" +
	"\vstatus_code\x18\n" +
	" \x01(\tR\n" +
	"statusCode\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12!\n" +
	"\fstatus_alias\x18\f \x01(\tR\vstatusAlias\x127\n" +
	"\tpickup_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bpickupAt\x12;\n" +
	"\vdelivery_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deliveryAt\x12\x14\n" +
	"\x05price\x18\x0f \x01(\x01R\x05price\x12\x1f\n" +
	"\vcurrency_id\x18\x10 \x01(\tR\n" +
	"currencyId\x12&\n" +
	"\x0fparent_order_id\x18\x11 \x01(\tR\rparentOrderId\x12\x18\n" +
	"\adeleted\x18\x12 \x01(\bR\adeleted\x12/\n" +
	"\x06detail\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x06detail\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfb\x01\n" +
	"\fOrderSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\tR\n" +
	"statusCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12,\n" +
	"\x12shipper_company_id\x18\x05 \x01(\tR\x10shipperCompanyId\x124\n" +
	"\x16transporter_company_id\x18\x06 \x01(\tR\x14transporterCompanyId\x12\x1b\n" +
	"\tdriver_id\x18\a \x01(\tR\bdriverId\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x10GetOrderResponse\x12.\n" +
	"\x05order\x18\x01 \x01(\v2\x18.karlo.business.v1.OrderR\x05order\"`\n" +
	"\x11ListOrdersRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.karlo.common.v1.QueryR\x05query\"~\n" +
	"\x12ListOrdersResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.karlo.business.v1.OrderR\x06orders\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.karlo.common.v1.PageInfoR\bpageInfo\"*\n" +
	"\x16GetOrderSummaryRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"X\n" +
	"\x17GetOrderSummaryResponse\x12=\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1f.karlo.business.v1.OrderSummaryR\tsummaries\"\xe3\x03\n" +
	"\tAgreement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10agreement_number\x18\x02 \x01(\tR\x0fagreementNumber\x12,\n" +
	"\x12shipper_company_id\x18\x03 \x01(\tR\x10shipperCompanyId\x124\n" +
	"\x16transporter_company_id\x18\x04 \x01(\tR\x14transporterCompanyId\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\tR\n" +
	"statusCode\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"valid_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x12;\n" +
	"\vvalid_until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12\x1a\n" +
	"\bverified\x18\t \x01(\bR\bverified\x12/\n" +
	"\x06detail\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x06detail\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"%\n" +
	"\x13GetAgreementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x14GetAgreementResponse\x12:\n" +
	"\tagreement\x18\x01 \x01(\v2\x1c.karlo.business.v1.AgreementR\tagreement\"\xc9\x03\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12,\n" +
	"\x12shipper_company_id\x18\x04 \x01(\tR\x10shipperCompanyId\x124\n" +
	"\x16transporter_company_id\x18\x05 \x01(\tR\x14transporterCompanyId\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\tR\n" +
	"statusCode\x12\x1a\n" +
	"\bsubtotal\x18\a \x01(\x01R\bsubtotal\x12\x10\n" +
	"\x03ppn\x18\b \x01(\x01R\x03ppn\x12\x14\n" +
	"\x05pph23\x18\t \x01(\x01R\x05pph23\x12\x14\n" +
	"\x05total\x18\n" +
	" \x01(\x01R\x05total\x12\x1f\n" +
	"\vcurrency_id\x18\v \x01(\tR\n" +
	"currencyId\x127\n" +
	"\tissued_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x123\n" +
	"\apaid_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x12GetInvoiceResponse\x124\n" +
	"\ainvoice\x18\x01 \x01(\v2\x1a.karlo.business.v1.InvoiceR\ainvoice\"\x86\x02\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x19\n" +
	"\btruck_id\x18\x04 \x01(\tR\atruckId\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\tR\n" +
	"statusCode\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"?\n" +
	" GetActiveShipmentByDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"r\n" +
	"!GetActiveShipmentByDriverResponse\x127\n" +
	"\bshipment\x18\x01 \x01(\v2\x1b.karlo.business.v1.ShipmentR\bshipment\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x9e\x02\n" +
	"\x1aReportGeofenceEventRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12E\n" +
	"\n" +
	"transition\x18\x03 \x01(\x0e2%.karlo.business.v1.GeofenceTransitionR\n" +
	"transition\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\"a\n" +
	"\x1bReportGeofenceEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12&\n" +
	"\x0fnew_status_code\x18\x02 \x01(\tR\rnewStatusCode*v\n" +
	"\x12GeofenceTransition\x12#\n" +
	"\x1fGEOFENCE_TRANSITION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GEOFENCE_TRANSITION_ENTER\x10\x01\x12\x1c\n" +
	"\x18GEOFENCE_TRANSITION_EXIT\x10\x022\xe6\x05\n" +
	"\x0fBusinessService\x12S\n" +
	"\bGetOrder\x12\".karlo.business.v1.GetOrderRequest\x1a#.karlo.business.v1.GetOrderResponse\x12Y\n" +
	"\n" +
	"ListOrders\x12$.karlo.business.v1.ListOrdersRequest\x1a%.karlo.business.v1.ListOrdersResponse\x12h\n" +
	"\x0fGetOrderSummary\x12).karlo.business.v1.GetOrderSummaryRequest\x1a*.karlo.business.v1.GetOrderSummaryResponse\x12_\n" +
	"\fGetAgreement\x12&.karlo.business.v1.GetAgreementRequest\x1a'.karlo.business.v1.GetAgreementResponse\x12Y\n" +
	"\n" +
	"GetInvoice\x12$.karlo.business.v1.GetInvoiceRequest\x1a%.karlo.business.v1.GetInvoiceResponse\x12\x86\x01\n" +
	"\x19GetActiveShipmentByDriver\x123.karlo.business.v1.GetActiveShipmentByDriverRequest\x1a4.karlo.business.v1.GetActiveShipmentByDriverResponse\x12t\n" +
	"\x13ReportGeofenceEvent\x12-.karlo.business.v1.ReportGeofenceEventRequest\x1a..karlo.business.v1.ReportGeofenceEventResponseB\xeb\x01\n" +
	"\x15com.karlo.business.v1B\rBusinessProtoP\x01Z]github.com/karlo/notification-service/internal/platform/genproto/karlo/business/v1;businessv1\xa2\x02\x03KBX\xaa\x02\x11Karlo.Business.V1\xca\x02\x11Karlo\\Business\\V1\xe2\x02\x1dKarlo\\Business\\V1\\GPBMetadata\xea\x02\x13Karlo::Business::V1b\x06proto3"

var (
	file_karlo_business_v1_business_proto_rawDescOnce sync.Once
	file_karlo_business_v1_business_proto_rawDescData []byte
)

func file_karlo_business_v1_business_proto_rawDescGZIP() []byte {
	file_karlo_business_v1_business_proto_rawDescOnce.Do(func() {
		file_karlo_business_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_karlo_business_v1_business_proto_rawDesc), len(file_karlo_business_v1_business_proto_rawDesc)))
	})
	return file_karlo_business_v1_business_proto_rawDescData
}

var file_karlo_business_v1_business_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_karlo_business_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_karlo_business_v1_business_proto_goTypes = []any{
	(GeofenceTransition)(0),                   // 0: karlo.business.v1.GeofenceTransition
	(*Order)(nil),                             // 1: karlo.business.v1.Order
	(*OrderSummary)(nil),                      // 2: karlo.business.v1.OrderSummary
	(*GetOrderRequest)(nil),                   // 3: karlo.business.v1.GetOrderRequest
	(*GetOrderResponse)(nil),                  // 4: karlo.business.v1.GetOrderResponse
	(*ListOrdersRequest)(nil),                 // 5: karlo.business.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),                // 6: karlo.business.v1.ListOrdersResponse
	(*GetOrderSummaryRequest)(nil),            // 7: karlo.business.v1.GetOrderSummaryRequest
	(*GetOrderSummaryResponse)(nil),           // 8: karlo.business.v1.GetOrderSummaryResponse
	(*Agreement)(nil),                         // 9: karlo.business.v1.Agreement
	(*GetAgreementRequest)(nil),               // 10: karlo.business.v1.GetAgreementRequest
	(*GetAgreementResponse)(nil),              // 11: karlo.business.v1.GetAgreementResponse
	(*Invoice)(nil),                           // 12: karlo.business.v1.Invoice
	(*GetInvoiceRequest)(nil),                 // 13: karlo.business.v1.GetInvoiceRequest
	(*GetInvoiceResponse)(nil),                // 14: karlo.business.v1.GetInvoiceResponse
	(*Shipment)(nil),                          // 15: karlo.business.v1.Shipment
	(*GetActiveShipmentByDriverRequest)(nil),  // 16: karlo.business.v1.GetActiveShipmentByDriverRequest
	(*GetActiveShipmentByDriverResponse)(nil), // 17: karlo.business.v1.GetActiveShipmentByDriverResponse
	(*ReportGeofenceEventRequest)(nil),        // 18: karlo.business.v1.ReportGeofenceEventRequest
	(*ReportGeofenceEventResponse)(nil),       // 19: karlo.business.v1.ReportGeofenceEventResponse
	(*timestamppb.Timestamp)(nil),             // 20: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                   // 21: google.protobuf.Struct
	(*v1.Query)(nil),                          // 22: karlo.common.v1.Query
	(*v1.PageInfo)(nil),                       // 23: karlo.common.v1.PageInfo
}
var file_karlo_business_v1_business_proto_depIdxs = []int32{
	20, // 0: karlo.business.v1.Order.pickup_at:type_name -> google.protobuf.Timestamp
	20, // 1: karlo.business.v1.Order.delivery_at:type_name -> google.protobuf.Timestamp
	21, // 2: karlo.business.v1.Order.detail:type_name -> google.protobuf.Struct
	20, // 3: karlo.business.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: karlo.business.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: karlo.business.v1.GetOrderResponse.order:type_name -> karlo.business.v1.Order
	22, // 6: karlo.business.v1.ListOrdersRequest.query:type_name -> karlo.common.v1.Query
	1,  // 7: karlo.business.v1.ListOrdersResponse.orders:type_name -> karlo.business.v1.Order
	23, // 8: karlo.business.v1.ListOrdersResponse.page_info:type_name -> karlo.common.v1.PageInfo
	2,  // 9: karlo.business.v1.GetOrderSummaryResponse.summaries:type_name -> karlo.business.v1.OrderSummary
	20, // 10: karlo.business.v1.Agreement.valid_from:type_name -> google.protobuf.Timestamp
	20, // 11: karlo.business.v1.Agreement.valid_until:type_name -> google.protobuf.Timestamp
	21, // 12: karlo.business.v1.Agreement.detail:type_name -> google.protobuf.Struct
	20, // 13: karlo.business.v1.Agreement.created_at:type_name -> google.protobuf.Timestamp
	9,  // 14: karlo.business.v1.GetAgreementResponse.agreement:type_name -> karlo.business.v1.Agreement
	20, // 15: karlo.business.v1.Invoice.issued_at:type_name -> google.protobuf.Timestamp
	20, // 16: karlo.business.v1.Invoice.paid_at:type_name -> google.protobuf.Timestamp
	12, // 17: karlo.business.v1.GetInvoiceResponse.invoice:type_name -> karlo.business.v1.Invoice
	20, // 18: karlo.business.v1.Shipment.started_at:type_name -> google.protobuf.Timestamp
	20, // 19: karlo.business.v1.Shipment.finished_at:type_name -> google.protobuf.Timestamp
	15, // 20: karlo.business.v1.GetActiveShipmentByDriverResponse.shipment:type_name -> karlo.business.v1.Shipment
	0,  // 21: karlo.business.v1.ReportGeofenceEventRequest.transition:type_name -> karlo.business.v1.GeofenceTransition
	20, // 22: karlo.business.v1.ReportGeofenceEventRequest.occurred_at:type_name -> google.protobuf.Timestamp
	3,  // 23: karlo.business.v1.BusinessService.GetOrder:input_type -> karlo.business.v1.GetOrderRequest
	5,  // 24: karlo.business.v1.BusinessService.ListOrders:input_type -> karlo.business.v1.ListOrdersRequest
	7,  // 25: karlo.business.v1.BusinessService.GetOrderSummary:input_type -> karlo.business.v1.GetOrderSummaryRequest
	10, // 26: karlo.business.v1.BusinessService.GetAgreement:input_type -> karlo.business.v1.GetAgreementRequest
	13, // 27: karlo.business.v1.BusinessService.GetInvoice:input_type -> karlo.business.v1.GetInvoiceRequest
	16, // 28: karlo.business.v1.BusinessService.GetActiveShipmentByDriver:input_type -> karlo.business.v1.GetActiveShipmentByDriverRequest
	18, // 29: karlo.business.v1.BusinessService.ReportGeofenceEvent:input_type -> karlo.business.v1.ReportGeofenceEventRequest
	4,  // 30: karlo.business.v1.BusinessService.GetOrder:output_type -> karlo.business.v1.GetOrderResponse
	6,  // 31: karlo.business.v1.BusinessService.ListOrders:output_type -> karlo.business.v1.ListOrdersResponse
	8,  // 32: karlo.business.v1.BusinessService.GetOrderSummary:output_type -> karlo.business.v1.GetOrderSummaryResponse
	11, // 33: karlo.business.v1.BusinessService.GetAgreement:output_type -> karlo.business.v1.GetAgreementResponse
	14, // 34: karlo.business.v1.BusinessService.GetInvoice:output_type -> karlo.business.v1.GetInvoiceResponse
	17, // 35: karlo.business.v1.BusinessService.GetActiveShipmentByDriver:output_type -> karlo.business.v1.GetActiveShipmentByDriverResponse
	19, // 36: karlo.business.v1.BusinessService.ReportGeofenceEvent:output_type -> karlo.business.v1.ReportGeofenceEventResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_karlo_business_v1_business_proto_init() }
func file_karlo_business_v1_business_proto_init() {
	if File_karlo_business_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_karlo_business_v1_business_proto_rawDesc), len(file_karlo_business_v1_business_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_karlo_business_v1_business_proto_goTypes,
		DependencyIndexes: file_karlo_business_v1_business_proto_depIdxs,
		EnumInfos:         file_karlo_business_v1_business_proto_enumTypes,
		MessageInfos:      file_karlo_business_v1_business_proto_msgTypes,
	}.Build()
	File_karlo_business_v1_business_proto = out.File
	file_karlo_business_v1_business_proto_goTypes = nil
	file_karlo_business_v1_business_proto_depIdxs = nil
}
