// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: karlo/masterdata/v1/masterdata.proto

package masterdatav1

import (
	v1 "github.com/karlo/notification-service/internal/platform/genproto/karlo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CatalogKind enumerates the global catalogues. Keeping them behind one RPC
// pair avoids twenty near-identical services; the kind selects the collection.
type CatalogKind int32

const (
	CatalogKind_CATALOG_KIND_UNSPECIFIED          CatalogKind = 0
	CatalogKind_CATALOG_KIND_BRAND                CatalogKind = 1
	CatalogKind_CATALOG_KIND_CARGO_TYPE           CatalogKind = 2
	CatalogKind_CATALOG_KIND_CARGO_TRUCK_CAPACITY CatalogKind = 3
	CatalogKind_CATALOG_KIND_CURRENCY             CatalogKind = 4
	CatalogKind_CATALOG_KIND_DISTRICT             CatalogKind = 5
	CatalogKind_CATALOG_KIND_ITEM                 CatalogKind = 6
	CatalogKind_CATALOG_KIND_ITEM_CHARACTER       CatalogKind = 7
	CatalogKind_CATALOG_KIND_ITEM_TYPE            CatalogKind = 8
	CatalogKind_CATALOG_KIND_KOTA                 CatalogKind = 9
	CatalogKind_CATALOG_KIND_PAYMENT_TYPE         CatalogKind = 10
	CatalogKind_CATALOG_KIND_PRICING_TYPE         CatalogKind = 11
	CatalogKind_CATALOG_KIND_PROVINSI             CatalogKind = 12
	CatalogKind_CATALOG_KIND_RATE_CARD            CatalogKind = 13
	CatalogKind_CATALOG_KIND_REQUIREMENT          CatalogKind = 14
	CatalogKind_CATALOG_KIND_ROUTE                CatalogKind = 15
	CatalogKind_CATALOG_KIND_TRUCK_BODY           CatalogKind = 16
	CatalogKind_CATALOG_KIND_TRUCK_HEAD           CatalogKind = 17
	CatalogKind_CATALOG_KIND_TRUCK_TYPE           CatalogKind = 18
	CatalogKind_CATALOG_KIND_FAQ                  CatalogKind = 19
	CatalogKind_CATALOG_KIND_JOB_VACANCY          CatalogKind = 20
)

// Enum value maps for CatalogKind.
var (
	CatalogKind_name = map[int32]string{
		0:  "CATALOG_KIND_UNSPECIFIED",
		1:  "CATALOG_KIND_BRAND",
		2:  "CATALOG_KIND_CARGO_TYPE",
		3:  "CATALOG_KIND_CARGO_TRUCK_CAPACITY",
		4:  "CATALOG_KIND_CURRENCY",
		5:  "CATALOG_KIND_DISTRICT",
		6:  "CATALOG_KIND_ITEM",
		7:  "CATALOG_KIND_ITEM_CHARACTER",
		8:  "CATALOG_KIND_ITEM_TYPE",
		9:  "CATALOG_KIND_KOTA",
		10: "CATALOG_KIND_PAYMENT_TYPE",
		11: "CATALOG_KIND_PRICING_TYPE",
		12: "CATALOG_KIND_PROVINSI",
		13: "CATALOG_KIND_RATE_CARD",
		14: "CATALOG_KIND_REQUIREMENT",
		15: "CATALOG_KIND_ROUTE",
		16: "CATALOG_KIND_TRUCK_BODY",
		17: "CATALOG_KIND_TRUCK_HEAD",
		18: "CATALOG_KIND_TRUCK_TYPE",
		19: "CATALOG_KIND_FAQ",
		20: "CATALOG_KIND_JOB_VACANCY",
	}
	CatalogKind_value = map[string]int32{
		"CATALOG_KIND_UNSPECIFIED":          0,
		"CATALOG_KIND_BRAND":                1,
		"CATALOG_KIND_CARGO_TYPE":           2,
		"CATALOG_KIND_CARGO_TRUCK_CAPACITY": 3,
		"CATALOG_KIND_CURRENCY":             4,
		"CATALOG_KIND_DISTRICT":             5,
		"CATALOG_KIND_ITEM":                 6,
		"CATALOG_KIND_ITEM_CHARACTER":       7,
		"CATALOG_KIND_ITEM_TYPE":            8,
		"CATALOG_KIND_KOTA":                 9,
		"CATALOG_KIND_PAYMENT_TYPE":         10,
		"CATALOG_KIND_PRICING_TYPE":         11,
		"CATALOG_KIND_PROVINSI":             12,
		"CATALOG_KIND_RATE_CARD":            13,
		"CATALOG_KIND_REQUIREMENT":          14,
		"CATALOG_KIND_ROUTE":                15,
		"CATALOG_KIND_TRUCK_BODY":           16,
		"CATALOG_KIND_TRUCK_HEAD":           17,
		"CATALOG_KIND_TRUCK_TYPE":           18,
		"CATALOG_KIND_FAQ":                  19,
		"CATALOG_KIND_JOB_VACANCY":          20,
	}
)

func (x CatalogKind) Enum() *CatalogKind {
	p := new(CatalogKind)
	*p = x
	return p
}

func (x CatalogKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatalogKind) Descriptor() protoreflect.EnumDescriptor {
	return file_karlo_masterdata_v1_masterdata_proto_enumTypes[0].Descriptor()
}

func (CatalogKind) Type() protoreflect.EnumType {
	return &file_karlo_masterdata_v1_masterdata_proto_enumTypes[0]
}

func (x CatalogKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatalogKind.Descriptor instead.
func (CatalogKind) EnumDescriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{0}
}

// CatalogItem is the common envelope over every global catalogue. The shared
// fields are promoted; everything catalogue-specific stays in attributes so a
// new catalogue does not require a contract change.
type CatalogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          CatalogKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=karlo.masterdata.v1.CatalogKind" json:"kind,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogItem) Reset() {
	*x = CatalogItem{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogItem) ProtoMessage() {}

func (x *CatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogItem.ProtoReflect.Descriptor instead.
func (*CatalogItem) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogItem) GetKind() CatalogKind {
	if x != nil {
		return x.Kind
	}
	return CatalogKind_CATALOG_KIND_UNSPECIFIED
}

func (x *CatalogItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CatalogItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatalogItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CatalogItem) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CatalogItem) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CatalogItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CatalogItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CatalogKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=karlo.masterdata.v1.CatalogKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemRequest) Reset() {
	*x = GetCatalogItemRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemRequest) ProtoMessage() {}

func (x *GetCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetCatalogItemRequest) GetKind() CatalogKind {
	if x != nil {
		return x.Kind
	}
	return CatalogKind_CATALOG_KIND_UNSPECIFIED
}

func (x *GetCatalogItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemResponse) Reset() {
	*x = GetCatalogItemResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemResponse) ProtoMessage() {}

func (x *GetCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatalogItemResponse) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListCatalogItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  CatalogKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=karlo.masterdata.v1.CatalogKind" json:"kind,omitempty"`
	Query *v1.Query              `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// parent_id filters hierarchical catalogues: cities within a province,
	// districts within a city.
	ParentId      string `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsRequest) Reset() {
	*x = ListCatalogItemsRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsRequest) ProtoMessage() {}

func (x *ListCatalogItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{3}
}

func (x *ListCatalogItemsRequest) GetKind() CatalogKind {
	if x != nil {
		return x.Kind
	}
	return CatalogKind_CATALOG_KIND_UNSPECIFIED
}

func (x *ListCatalogItemsRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ListCatalogItemsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListCatalogItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsResponse) Reset() {
	*x = ListCatalogItemsResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsResponse) ProtoMessage() {}

func (x *ListCatalogItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{4}
}

func (x *ListCatalogItemsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCatalogItemsResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// CatalogRef names one entry to resolve.
type CatalogRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CatalogKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=karlo.masterdata.v1.CatalogKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogRef) Reset() {
	*x = CatalogRef{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogRef) ProtoMessage() {}

func (x *CatalogRef) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogRef.ProtoReflect.Descriptor instead.
func (*CatalogRef) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{5}
}

func (x *CatalogRef) GetKind() CatalogKind {
	if x != nil {
		return x.Kind
	}
	return CatalogKind_CATALOG_KIND_UNSPECIFIED
}

func (x *CatalogRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveCatalogItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*CatalogRef          `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCatalogItemsRequest) Reset() {
	*x = ResolveCatalogItemsRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCatalogItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCatalogItemsRequest) ProtoMessage() {}

func (x *ResolveCatalogItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCatalogItemsRequest.ProtoReflect.Descriptor instead.
func (*ResolveCatalogItemsRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveCatalogItemsRequest) GetRefs() []*CatalogRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ResolveCatalogItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCatalogItemsResponse) Reset() {
	*x = ResolveCatalogItemsResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCatalogItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCatalogItemsResponse) ProtoMessage() {}

func (x *ResolveCatalogItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCatalogItemsResponse.ProtoReflect.Descriptor instead.
func (*ResolveCatalogItemsResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveCatalogItemsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ValidateReferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*CatalogRef          `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReferencesRequest) Reset() {
	*x = ValidateReferencesRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReferencesRequest) ProtoMessage() {}

func (x *ValidateReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReferencesRequest.ProtoReflect.Descriptor instead.
func (*ValidateReferencesRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateReferencesRequest) GetRefs() []*CatalogRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ValidateReferencesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// invalid lists the refs that could not be resolved.
	Invalid       []*CatalogRef `protobuf:"bytes,2,rep,name=invalid,proto3" json:"invalid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReferencesResponse) Reset() {
	*x = ValidateReferencesResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReferencesResponse) ProtoMessage() {}

func (x *ValidateReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReferencesResponse.ProtoReflect.Descriptor instead.
func (*ValidateReferencesResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateReferencesResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateReferencesResponse) GetInvalid() []*CatalogRef {
	if x != nil {
		return x.Invalid
	}
	return nil
}

// Truck is company-owned master data: the vehicle register.
type Truck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	PoliceNumber  string                 `protobuf:"bytes,3,opt,name=police_number,json=policeNumber,proto3" json:"police_number,omitempty"`
	TruckTypeId   string                 `protobuf:"bytes,4,opt,name=truck_type_id,json=truckTypeId,proto3" json:"truck_type_id,omitempty"`
	TruckHeadId   string                 `protobuf:"bytes,5,opt,name=truck_head_id,json=truckHeadId,proto3" json:"truck_head_id,omitempty"`
	TruckBodyId   string                 `protobuf:"bytes,6,opt,name=truck_body_id,json=truckBodyId,proto3" json:"truck_body_id,omitempty"`
	BrandId       string                 `protobuf:"bytes,7,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Year          int32                  `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	ChassisNumber string                 `protobuf:"bytes,9,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	EngineNumber  string                 `protobuf:"bytes,10,opt,name=engine_number,json=engineNumber,proto3" json:"engine_number,omitempty"`
	// driver_ids are the drivers currently paired with this truck.
	DriverIds     []string               `protobuf:"bytes,11,rep,name=driver_ids,json=driverIds,proto3" json:"driver_ids,omitempty"`
	TruckGroupId  string                 `protobuf:"bytes,12,opt,name=truck_group_id,json=truckGroupId,proto3" json:"truck_group_id,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,14,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Documents     *structpb.Struct       `protobuf:"bytes,15,opt,name=documents,proto3" json:"documents,omitempty"`
	Deleted       bool                   `protobuf:"varint,16,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Truck) Reset() {
	*x = Truck{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Truck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Truck) ProtoMessage() {}

func (x *Truck) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Truck.ProtoReflect.Descriptor instead.
func (*Truck) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{10}
}

func (x *Truck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Truck) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Truck) GetPoliceNumber() string {
	if x != nil {
		return x.PoliceNumber
	}
	return ""
}

func (x *Truck) GetTruckTypeId() string {
	if x != nil {
		return x.TruckTypeId
	}
	return ""
}

func (x *Truck) GetTruckHeadId() string {
	if x != nil {
		return x.TruckHeadId
	}
	return ""
}

func (x *Truck) GetTruckBodyId() string {
	if x != nil {
		return x.TruckBodyId
	}
	return ""
}

func (x *Truck) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Truck) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Truck) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *Truck) GetEngineNumber() string {
	if x != nil {
		return x.EngineNumber
	}
	return ""
}

func (x *Truck) GetDriverIds() []string {
	if x != nil {
		return x.DriverIds
	}
	return nil
}

func (x *Truck) GetTruckGroupId() string {
	if x != nil {
		return x.TruckGroupId
	}
	return ""
}

func (x *Truck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Truck) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Truck) GetDocuments() *structpb.Struct {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Truck) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Truck) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Truck) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetTruckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTruckRequest) Reset() {
	*x = GetTruckRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTruckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTruckRequest) ProtoMessage() {}

func (x *GetTruckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTruckRequest.ProtoReflect.Descriptor instead.
func (*GetTruckRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{11}
}

func (x *GetTruckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTruckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Truck         *Truck                 `protobuf:"bytes,1,opt,name=truck,proto3" json:"truck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTruckResponse) Reset() {
	*x = GetTruckResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTruckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTruckResponse) ProtoMessage() {}

func (x *GetTruckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTruckResponse.ProtoReflect.Descriptor instead.
func (*GetTruckResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{12}
}

func (x *GetTruckResponse) GetTruck() *Truck {
	if x != nil {
		return x.Truck
	}
	return nil
}

type ListTrucksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Query         *v1.Query              `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrucksRequest) Reset() {
	*x = ListTrucksRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrucksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrucksRequest) ProtoMessage() {}

func (x *ListTrucksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrucksRequest.ProtoReflect.Descriptor instead.
func (*ListTrucksRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{13}
}

func (x *ListTrucksRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListTrucksRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListTrucksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trucks        []*Truck               `protobuf:"bytes,1,rep,name=trucks,proto3" json:"trucks,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrucksResponse) Reset() {
	*x = ListTrucksResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrucksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrucksResponse) ProtoMessage() {}

func (x *ListTrucksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrucksResponse.ProtoReflect.Descriptor instead.
func (*ListTrucksResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{14}
}

func (x *ListTrucksResponse) GetTrucks() []*Truck {
	if x != nil {
		return x.Trucks
	}
	return nil
}

func (x *ListTrucksResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetTrucksByDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrucksByDriverRequest) Reset() {
	*x = GetTrucksByDriverRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrucksByDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrucksByDriverRequest) ProtoMessage() {}

func (x *GetTrucksByDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrucksByDriverRequest.ProtoReflect.Descriptor instead.
func (*GetTrucksByDriverRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{15}
}

func (x *GetTrucksByDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetTrucksByDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trucks        []*Truck               `protobuf:"bytes,1,rep,name=trucks,proto3" json:"trucks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrucksByDriverResponse) Reset() {
	*x = GetTrucksByDriverResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrucksByDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrucksByDriverResponse) ProtoMessage() {}

func (x *GetTrucksByDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrucksByDriverResponse.ProtoReflect.Descriptor instead.
func (*GetTrucksByDriverResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{16}
}

func (x *GetTrucksByDriverResponse) GetTrucks() []*Truck {
	if x != nil {
		return x.Trucks
	}
	return nil
}

// Warehouse is company-owned master data: loading and unloading points.
type Warehouse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId  string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address    string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CityId     string                 `protobuf:"bytes,5,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	ProvinceId string                 `protobuf:"bytes,6,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Latitude   float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude  float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// geofence_radius_meters drives the finish-with-geofencing company setting.
	GeofenceRadiusMeters int32                  `protobuf:"varint,9,opt,name=geofence_radius_meters,json=geofenceRadiusMeters,proto3" json:"geofence_radius_meters,omitempty"`
	PicName              string                 `protobuf:"bytes,10,opt,name=pic_name,json=picName,proto3" json:"pic_name,omitempty"`
	PicPhone             string                 `protobuf:"bytes,11,opt,name=pic_phone,json=picPhone,proto3" json:"pic_phone,omitempty"`
	Deleted              bool                   `protobuf:"varint,12,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{17}
}

func (x *Warehouse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Warehouse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Warehouse) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *Warehouse) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *Warehouse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Warehouse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Warehouse) GetGeofenceRadiusMeters() int32 {
	if x != nil {
		return x.GeofenceRadiusMeters
	}
	return 0
}

func (x *Warehouse) GetPicName() string {
	if x != nil {
		return x.PicName
	}
	return ""
}

func (x *Warehouse) GetPicPhone() string {
	if x != nil {
		return x.PicPhone
	}
	return ""
}

func (x *Warehouse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Warehouse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Warehouse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseRequest) Reset() {
	*x = GetWarehouseRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseRequest) ProtoMessage() {}

func (x *GetWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseRequest.ProtoReflect.Descriptor instead.
func (*GetWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{18}
}

func (x *GetWarehouseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouse     *Warehouse             `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseResponse) Reset() {
	*x = GetWarehouseResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseResponse) ProtoMessage() {}

func (x *GetWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseResponse.ProtoReflect.Descriptor instead.
func (*GetWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{19}
}

func (x *GetWarehouseResponse) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

type ListWarehousesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Query         *v1.Query              `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesRequest) Reset() {
	*x = ListWarehousesRequest{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesRequest) ProtoMessage() {}

func (x *ListWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesRequest.ProtoReflect.Descriptor instead.
func (*ListWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{20}
}

func (x *ListWarehousesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListWarehousesRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListWarehousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesResponse) Reset() {
	*x = ListWarehousesResponse{}
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesResponse) ProtoMessage() {}

func (x *ListWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_masterdata_v1_masterdata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesResponse.ProtoReflect.Descriptor instead.
func (*ListWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP(), []int{21}
}

func (x *ListWarehousesResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

func (x *ListWarehousesResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_karlo_masterdata_v1_masterdata_proto protoreflect.FileDescriptor

const file_karlo_masterdata_v1_masterdata_proto_rawDesc = "" +
	"\n" +
	"$karlo/masterdata/v1/masterdata.proto\x12\x13karlo.masterdata.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ckarlo/common/v1/common.proto\"\xe4\x02\n" +
	"\vCatalogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x04kind\x18\x02 \x01(\x0e2 .karlo.masterdata.v1.CatalogKindR\x04kind\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x127\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"]\n" +
	"\x15GetCatalogItemRequest\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .karlo.masterdata.v1.CatalogKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"N\n" +
	"\x16GetCatalogItemResponse\x124\n" +
	"\x04item\x18\x01 \x01(\v2 .karlo.masterdata.v1.CatalogItemR\x04item\"\x9a\x01\n" +
	"\x17ListCatalogItemsRequest\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .karlo.masterdata.v1.CatalogKindR\x04kind\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.karlo.common.v1.QueryR\x05query\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\"\x8a\x01\n" +
	"\x18ListCatalogItemsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .karlo.masterdata.v1.CatalogItemR\x05items\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.karlo.common.v1.PageInfoR\bpageInfo\"R\n" +
	"\n" +
	"CatalogRef\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .karlo.masterdata.v1.CatalogKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Q\n" +
	"\x1aResolveCatalogItemsRequest\x123\n" +
	"\x04refs\x18\x01 \x03(\v2\x1f.karlo.masterdata.v1.CatalogRefR\x04refs\"U\n" +
	"\x1bResolveCatalogItemsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .karlo.masterdata.v1.CatalogItemR\x05items\"P\n" +
	"\x19ValidateReferencesRequest\x123\n" +
	"\x04refs\x18\x01 \x03(\v2\x1f.karlo.masterdata.v1.CatalogRefR\x04refs\"m\n" +
	"\x1aValidateReferencesResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x129\n" +
	"\ainvalid\x18\x02 \x03(\v2\x1f.karlo.masterdata.v1.CatalogRefR\ainvalid\"\x89\x05\n" +
	"\x05Truck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12#\n" +
	"\rpolice_number\x18\x03 \x01(\tR\fpoliceNumber\x12\"\n" +
	"\rtruck_type_id\x18\x04 \x01(\tR\vtruckTypeId\x12\"\n" +
	"\rtruck_head_id\x18\x05 \x01(\tR\vtruckHeadId\x12\"\n" +
	"\rtruck_body_id\x18\x06 \x01(\tR\vtruckBodyId\x12\x19\n" +
	"\bbrand_id\x18\a \x01(\tR\abrandId\x12\x12\n" +
	"\x04year\x18\b \x01(\x05R\x04year\x12%\n" +
	"\x0echassis_number\x18\t \x01(\tR\rchassisNumber\x12#\n" +
	"\rengine_number\x18\n" +
	" \x01(\tR\fengineNumber\x12\x1d\n" +
	"\n" +
	"driver_ids\x18\v \x03(\tR\tdriverIds\x12$\n" +
	"\x0etruck_group_id\x18\f \x01(\tR\ftruckGroupId\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12!\n" +
	"\fis_available\x18\x0e \x01(\bR\visAvailable\x125\n" +
	"\tdocuments\x18\x0f \x01(\v2\x17.google.protobuf.StructR\tdocuments\x12\x18\n" +
	"\adeleted\x18\x10 \x01(\bR\adeleted\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"!\n" +
	"\x0fGetTruckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10GetTruckResponse\x120\n" +
	"\x05truck\x18\x01 \x01(\v2\x1a.karlo.masterdata.v1.TruckR\x05truck\"`\n" +
	"\x11ListTrucksRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.karlo.common.v1.QueryR\x05query\"\x80\x01\n" +
	"\x12ListTrucksResponse\x122\n" +
	"\x06trucks\x18\x01 \x03(\v2\x1a.karlo.masterdata.v1.TruckR\x06trucks\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.karlo.common.v1.PageInfoR\bpageInfo\"7\n" +
	"\x18GetTrucksByDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"O\n" +
	"\x19GetTrucksByDriverResponse\x122\n" +
	"\x06trucks\x18\x01 \x03(\v2\x1a.karlo.masterdata.v1.TruckR\x06trucks\"\xda\x03\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x17\n" +
	"\acity_id\x18\x05 \x01(\tR\x06cityId\x12\x1f\n" +
	"\vprovince_id\x18\x06 \x01(\tR\n" +
	"provinceId\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x124\n" +
	"\x16geofence_radius_meters\x18\t \x01(\x05R\x14geofenceRadiusMeters\x12\x19\n" +
	"\bpic_name\x18\n" +
	" \x01(\tR\apicName\x12\x1b\n" +
	"\tpic_phone\x18\v \x01(\tR\bpicPhone\x12\x18\n" +
	"\adeleted\x18\f \x01(\bR\adeleted\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"%\n" +
	"\x13GetWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x14GetWarehouseResponse\x12<\n" +
	"\twarehouse\x18\x01 \x01(\v2\x1e.karlo.masterdata.v1.WarehouseR\twarehouse\"d\n" +
	"\x15ListWarehousesRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.karlo.common.v1.QueryR\x05query\"\x90\x01\n" +
	"\x16ListWarehousesResponse\x12>\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x1e.karlo.masterdata.v1.WarehouseR\n" +
	"warehouses\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.karlo.common.v1.PageInfoR\bpageInfo*\xde\x04\n" +
	"\vCatalogKind\x12\x1c\n" +
	"\x18CATALOG_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CATALOG_KIND_BRAND\x10\x01\x12\x1b\n" +
	"\x17CATALOG_KIND_CARGO_TYPE\x10\x02\x12%\n" +
	"!CATALOG_KIND_CARGO_TRUCK_CAPACITY\x10\x03\x12\x19\n" +
	"\x15CATALOG_KIND_CURRENCY\x10\x04\x12\x19\n" +
	"\x15CATALOG_KIND_DISTRICT\x10\x05\x12\x15\n" +
	"\x11CATALOG_KIND_ITEM\x10\x06\x12\x1f\n" +
	"\x1bCATALOG_KIND_ITEM_CHARACTER\x10\a\x12\x1a\n" +
	"\x16CATALOG_KIND_ITEM_TYPE\x10\b\x12\x15\n" +
	"\x11CATALOG_KIND_KOTA\x10\t\x12\x1d\n" +
	"\x19CATALOG_KIND_PAYMENT_TYPE\x10\n" +
	"\x12\x1d\n" +
	"\x19CATALOG_KIND_PRICING_TYPE\x10\v\x12\x19\n" +
	"\x15CATALOG_KIND_PROVINSI\x10\f\x12\x1a\n" +
	"\x16CATALOG_KIND_RATE_CARD\x10\r\x12\x1c\n" +
	"\x18CATALOG_KIND_REQUIREMENT\x10\x0e\x12\x16\n" +
	"\x12CATALOG_KIND_ROUTE\x10\x0f\x12\x1b\n" +
	"\x17CATALOG_KIND_TRUCK_BODY\x10\x10\x12\x1b\n" +
	"\x17CATALOG_KIND_TRUCK_HEAD\x10\x11\x12\x1b\n" +
	"\x17CATALOG_KIND_TRUCK_TYPE\x10\x12\x12\x14\n" +
	"\x10CATALOG_KIND_FAQ\x10\x13\x12\x1c\n" +
	"\x18CATALOG_KIND_JOB_VACANCY\x10\x142\xdc\a\n" +
	"\x11MasterDataService\x12i\n" +
	"\x0eGetCatalogItem\x12*.karlo.masterdata.v1.GetCatalogItemRequest\x1a+.karlo.masterdata.v1.GetCatalogItemResponse\x12o\n" +
	"\x10ListCatalogItems\x12,.karlo.masterdata.v1.ListCatalogItemsRequest\x1a-.karlo.masterdata.v1.ListCatalogItemsResponse\x12x\n" +
	"\x13ResolveCatalogItems\x12/.karlo.masterdata.v1.ResolveCatalogItemsRequest\x1a0.karlo.masterdata.v1.ResolveCatalogItemsResponse\x12u\n" +
	"\x12ValidateReferences\x12..karlo.masterdata.v1.ValidateReferencesRequest\x1a/.karlo.masterdata.v1.ValidateReferencesResponse\x12W\n" +
	"\bGetTruck\x12$.karlo.masterdata.v1.GetTruckRequest\x1a%.karlo.masterdata.v1.GetTruckResponse\x12]\n" +
	"\n" +
	"ListTrucks\x12&.karlo.masterdata.v1.ListTrucksRequest\x1a'.karlo.masterdata.v1.ListTrucksResponse\x12r\n" +
	"\x11GetTrucksByDriver\x12-.karlo.masterdata.v1.GetTrucksByDriverRequest\x1a..karlo.masterdata.v1.GetTrucksByDriverResponse\x12c\n" +
	"\fGetWarehouse\x12(.karlo.masterdata.v1.GetWarehouseRequest\x1a).karlo.masterdata.v1.GetWarehouseResponse\x12i\n" +
	"\x0eListWarehouses\x12*.karlo.masterdata.v1.ListWarehousesRequest\x1a+.karlo.masterdata.v1.ListWarehousesResponseB\xe4\x01\n" +
	"\x17com.karlo.masterdata.v1B\x0fMasterdataProtoP\x01ZJgithub.com/karlo/notification-service/internal/platform/genproto/karlo/masterdata/v1;masterdatav1\xa2\x02\x03KMX\xaa\x02\x13Karlo.Masterdata.V1\xca\x02\x13Karlo\\Masterdata\\V1\xe2\x02\x1fKarlo\\Masterdata\\V1\\GPBMetadata\xea\x02\x15Karlo::Masterdata::V1b\x06proto3"

var (
	file_karlo_masterdata_v1_masterdata_proto_rawDescOnce sync.Once
	file_karlo_masterdata_v1_masterdata_proto_rawDescData []byte
)

func file_karlo_masterdata_v1_masterdata_proto_rawDescGZIP() []byte {
	file_karlo_masterdata_v1_masterdata_proto_rawDescOnce.Do(func() {
		file_karlo_masterdata_v1_masterdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_karlo_masterdata_v1_masterdata_proto_rawDesc), len(file_karlo_masterdata_v1_masterdata_proto_rawDesc)))
	})
	return file_karlo_masterdata_v1_masterdata_proto_rawDescData
}

var file_karlo_masterdata_v1_masterdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_karlo_masterdata_v1_masterdata_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_karlo_masterdata_v1_masterdata_proto_goTypes = []any{
	(CatalogKind)(0),                    // 0: karlo.masterdata.v1.CatalogKind
	(*CatalogItem)(nil),                 // 1: karlo.masterdata.v1.CatalogItem
	(*GetCatalogItemRequest)(nil),       // 2: karlo.masterdata.v1.GetCatalogItemRequest
	(*GetCatalogItemResponse)(nil),      // 3: karlo.masterdata.v1.GetCatalogItemResponse
	(*ListCatalogItemsRequest)(nil),     // 4: karlo.masterdata.v1.ListCatalogItemsRequest
	(*ListCatalogItemsResponse)(nil),    // 5: karlo.masterdata.v1.ListCatalogItemsResponse
	(*CatalogRef)(nil),                  // 6: karlo.masterdata.v1.CatalogRef
	(*ResolveCatalogItemsRequest)(nil),  // 7: karlo.masterdata.v1.ResolveCatalogItemsRequest
	(*ResolveCatalogItemsResponse)(nil), // 8: karlo.masterdata.v1.ResolveCatalogItemsResponse
	(*ValidateReferencesRequest)(nil),   // 9: karlo.masterdata.v1.ValidateReferencesRequest
	(*ValidateReferencesResponse)(nil),  // 10: karlo.masterdata.v1.ValidateReferencesResponse
	(*Truck)(nil),                       // 11: karlo.masterdata.v1.Truck
	(*GetTruckRequest)(nil),             // 12: karlo.masterdata.v1.GetTruckRequest
	(*GetTruckResponse)(nil),            // 13: karlo.masterdata.v1.GetTruckResponse
	(*ListTrucksRequest)(nil),           // 14: karlo.masterdata.v1.ListTrucksRequest
	(*ListTrucksResponse)(nil),          // 15: karlo.masterdata.v1.ListTrucksResponse
	(*GetTrucksByDriverRequest)(nil),    // 16: karlo.masterdata.v1.GetTrucksByDriverRequest
	(*GetTrucksByDriverResponse)(nil),   // 17: karlo.masterdata.v1.GetTrucksByDriverResponse
	(*Warehouse)(nil),                   // 18: karlo.masterdata.v1.Warehouse
	(*GetWarehouseRequest)(nil),         // 19: karlo.masterdata.v1.GetWarehouseRequest
	(*GetWarehouseResponse)(nil),        // 20: karlo.masterdata.v1.GetWarehouseResponse
	(*ListWarehousesRequest)(nil),       // 21: karlo.masterdata.v1.ListWarehousesRequest
	(*ListWarehousesResponse)(nil),      // 22: karlo.masterdata.v1.ListWarehousesResponse
	(*structpb.Struct)(nil),             // 23: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*v1.Query)(nil),                    // 25: karlo.common.v1.Query
	(*v1.PageInfo)(nil),                 // 26: karlo.common.v1.PageInfo
}
var file_karlo_masterdata_v1_masterdata_proto_depIdxs = []int32{
	0,  // 0: karlo.masterdata.v1.CatalogItem.kind:type_name -> karlo.masterdata.v1.CatalogKind
	23, // 1: karlo.masterdata.v1.CatalogItem.attributes:type_name -> google.protobuf.Struct
	24, // 2: karlo.masterdata.v1.CatalogItem.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: karlo.masterdata.v1.CatalogItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: karlo.masterdata.v1.GetCatalogItemRequest.kind:type_name -> karlo.masterdata.v1.CatalogKind
	1,  // 5: karlo.masterdata.v1.GetCatalogItemResponse.item:type_name -> karlo.masterdata.v1.CatalogItem
	0,  // 6: karlo.masterdata.v1.ListCatalogItemsRequest.kind:type_name -> karlo.masterdata.v1.CatalogKind
	25, // 7: karlo.masterdata.v1.ListCatalogItemsRequest.query:type_name -> karlo.common.v1.Query
	1,  // 8: karlo.masterdata.v1.ListCatalogItemsResponse.items:type_name -> karlo.masterdata.v1.CatalogItem
	26, // 9: karlo.masterdata.v1.ListCatalogItemsResponse.page_info:type_name -> karlo.common.v1.PageInfo
	0,  // 10: karlo.masterdata.v1.CatalogRef.kind:type_name -> karlo.masterdata.v1.CatalogKind
	6,  // 11: karlo.masterdata.v1.ResolveCatalogItemsRequest.refs:type_name -> karlo.masterdata.v1.CatalogRef
	1,  // 12: karlo.masterdata.v1.ResolveCatalogItemsResponse.items:type_name -> karlo.masterdata.v1.CatalogItem
	6,  // 13: karlo.masterdata.v1.ValidateReferencesRequest.refs:type_name -> karlo.masterdata.v1.CatalogRef
	6,  // 14: karlo.masterdata.v1.ValidateReferencesResponse.invalid:type_name -> karlo.masterdata.v1.CatalogRef
	23, // 15: karlo.masterdata.v1.Truck.documents:type_name -> google.protobuf.Struct
	24, // 16: karlo.masterdata.v1.Truck.created_at:type_name -> google.protobuf.Timestamp
	24, // 17: karlo.masterdata.v1.Truck.updated_at:type_name -> google.protobuf.Timestamp
	11, // 18: karlo.masterdata.v1.GetTruckResponse.truck:type_name -> karlo.masterdata.v1.Truck
	25, // 19: karlo.masterdata.v1.ListTrucksRequest.query:type_name -> karlo.common.v1.Query
	11, // 20: karlo.masterdata.v1.ListTrucksResponse.trucks:type_name -> karlo.masterdata.v1.Truck
	26, // 21: karlo.masterdata.v1.ListTrucksResponse.page_info:type_name -> karlo.common.v1.PageInfo
	11, // 22: karlo.masterdata.v1.GetTrucksByDriverResponse.trucks:type_name -> karlo.masterdata.v1.Truck
	24, // 23: karlo.masterdata.v1.Warehouse.created_at:type_name -> google.protobuf.Timestamp
	24, // 24: karlo.masterdata.v1.Warehouse.updated_at:type_name -> google.protobuf.Timestamp
	18, // 25: karlo.masterdata.v1.GetWarehouseResponse.warehouse:type_name -> karlo.masterdata.v1.Warehouse
	25, // 26: karlo.masterdata.v1.ListWarehousesRequest.query:type_name -> karlo.common.v1.Query
	18, // 27: karlo.masterdata.v1.ListWarehousesResponse.warehouses:type_name -> karlo.masterdata.v1.Warehouse
	26, // 28: karlo.masterdata.v1.ListWarehousesResponse.page_info:type_name -> karlo.common.v1.PageInfo
	2,  // 29: karlo.masterdata.v1.MasterDataService.GetCatalogItem:input_type -> karlo.masterdata.v1.GetCatalogItemRequest
	4,  // 30: karlo.masterdata.v1.MasterDataService.ListCatalogItems:input_type -> karlo.masterdata.v1.ListCatalogItemsRequest
	7,  // 31: karlo.masterdata.v1.MasterDataService.ResolveCatalogItems:input_type -> karlo.masterdata.v1.ResolveCatalogItemsRequest
	9,  // 32: karlo.masterdata.v1.MasterDataService.ValidateReferences:input_type -> karlo.masterdata.v1.ValidateReferencesRequest
	12, // 33: karlo.masterdata.v1.MasterDataService.GetTruck:input_type -> karlo.masterdata.v1.GetTruckRequest
	14, // 34: karlo.masterdata.v1.MasterDataService.ListTrucks:input_type -> karlo.masterdata.v1.ListTrucksRequest
	16, // 35: karlo.masterdata.v1.MasterDataService.GetTrucksByDriver:input_type -> karlo.masterdata.v1.GetTrucksByDriverRequest
	19, // 36: karlo.masterdata.v1.MasterDataService.GetWarehouse:input_type -> karlo.masterdata.v1.GetWarehouseRequest
	21, // 37: karlo.masterdata.v1.MasterDataService.ListWarehouses:input_type -> karlo.masterdata.v1.ListWarehousesRequest
	3,  // 38: karlo.masterdata.v1.MasterDataService.GetCatalogItem:output_type -> karlo.masterdata.v1.GetCatalogItemResponse
	5,  // 39: karlo.masterdata.v1.MasterDataService.ListCatalogItems:output_type -> karlo.masterdata.v1.ListCatalogItemsResponse
	8,  // 40: karlo.masterdata.v1.MasterDataService.ResolveCatalogItems:output_type -> karlo.masterdata.v1.ResolveCatalogItemsResponse
	10, // 41: karlo.masterdata.v1.MasterDataService.ValidateReferences:output_type -> karlo.masterdata.v1.ValidateReferencesResponse
	13, // 42: karlo.masterdata.v1.MasterDataService.GetTruck:output_type -> karlo.masterdata.v1.GetTruckResponse
	15, // 43: karlo.masterdata.v1.MasterDataService.ListTrucks:output_type -> karlo.masterdata.v1.ListTrucksResponse
	17, // 44: karlo.masterdata.v1.MasterDataService.GetTrucksByDriver:output_type -> karlo.masterdata.v1.GetTrucksByDriverResponse
	20, // 45: karlo.masterdata.v1.MasterDataService.GetWarehouse:output_type -> karlo.masterdata.v1.GetWarehouseResponse
	22, // 46: karlo.masterdata.v1.MasterDataService.ListWarehouses:output_type -> karlo.masterdata.v1.ListWarehousesResponse
	38, // [38:47] is the sub-list for method output_type
	29, // [29:38] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_karlo_masterdata_v1_masterdata_proto_init() }
func file_karlo_masterdata_v1_masterdata_proto_init() {
	if File_karlo_masterdata_v1_masterdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_karlo_masterdata_v1_masterdata_proto_rawDesc), len(file_karlo_masterdata_v1_masterdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_karlo_masterdata_v1_masterdata_proto_goTypes,
		DependencyIndexes: file_karlo_masterdata_v1_masterdata_proto_depIdxs,
		EnumInfos:         file_karlo_masterdata_v1_masterdata_proto_enumTypes,
		MessageInfos:      file_karlo_masterdata_v1_masterdata_proto_msgTypes,
	}.Build()
	File_karlo_masterdata_v1_masterdata_proto = out.File
	file_karlo_masterdata_v1_masterdata_proto_goTypes = nil
	file_karlo_masterdata_v1_masterdata_proto_depIdxs = nil
}
