// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: karlo/masterdata/v1/masterdata.proto

package masterdatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterDataService_GetCatalogItem_FullMethodName      = "/karlo.masterdata.v1.MasterDataService/GetCatalogItem"
	MasterDataService_ListCatalogItems_FullMethodName    = "/karlo.masterdata.v1.MasterDataService/ListCatalogItems"
	MasterDataService_ResolveCatalogItems_FullMethodName = "/karlo.masterdata.v1.MasterDataService/ResolveCatalogItems"
	MasterDataService_ValidateReferences_FullMethodName  = "/karlo.masterdata.v1.MasterDataService/ValidateReferences"
	MasterDataService_GetTruck_FullMethodName            = "/karlo.masterdata.v1.MasterDataService/GetTruck"
	MasterDataService_ListTrucks_FullMethodName          = "/karlo.masterdata.v1.MasterDataService/ListTrucks"
	MasterDataService_ListDrivers_FullMethodName         = "/karlo.masterdata.v1.MasterDataService/ListDrivers"
	MasterDataService_GetDriver_FullMethodName           = "/karlo.masterdata.v1.MasterDataService/GetDriver"
	MasterDataService_GetTrucksByDriver_FullMethodName   = "/karlo.masterdata.v1.MasterDataService/GetTrucksByDriver"
	MasterDataService_GetWarehouse_FullMethodName        = "/karlo.masterdata.v1.MasterDataService/GetWarehouse"
	MasterDataService_ListWarehouses_FullMethodName      = "/karlo.masterdata.v1.MasterDataService/ListWarehouses"
)

// MasterDataServiceClient is the client API for MasterDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MasterDataService owns reference data. It splits into two families:
//
//	Global catalogues  - truck types, cargo types, item types, provinces,
//	                     cities, currencies. Shared by every company, edited
//	                     by Karlo staff.
//	Company catalogues - trucks, truck groups, warehouses, customers, points,
//	                     saved routes. Owned by one company, edited by that
//	                     company.
//
// Both live in MongoDB because the shapes are heterogeneous and read-mostly.
type MasterDataServiceClient interface {
	// GetCatalogItem resolves one entry from a global catalogue.
	GetCatalogItem(ctx context.Context, in *GetCatalogItemRequest, opts ...grpc.CallOption) (*GetCatalogItemResponse, error)
	// ListCatalogItems pages through a global catalogue.
	ListCatalogItems(ctx context.Context, in *ListCatalogItemsRequest, opts ...grpc.CallOption) (*ListCatalogItemsResponse, error)
	// ResolveCatalogItems batch-resolves catalogue references so a caller can
	// denormalise many foreign keys in one round trip. Callers that render an
	// order list use this instead of one lookup per row.
	ResolveCatalogItems(ctx context.Context, in *ResolveCatalogItemsRequest, opts ...grpc.CallOption) (*ResolveCatalogItemsResponse, error)
	// ValidateReferences checks that a set of catalogue references exists before
	// the business service commits a write. Returns the invalid ones.
	ValidateReferences(ctx context.Context, in *ValidateReferencesRequest, opts ...grpc.CallOption) (*ValidateReferencesResponse, error)
	GetTruck(ctx context.Context, in *GetTruckRequest, opts ...grpc.CallOption) (*GetTruckResponse, error)
	ListTrucks(ctx context.Context, in *ListTrucksRequest, opts ...grpc.CallOption) (*ListTrucksResponse, error)
	// ListDrivers pages a company's driver register, for a service that keeps
	// a projection of it — FMS's driversync. updated_since makes it
	// incremental; deleted rows are included so a projection can retire them.
	ListDrivers(ctx context.Context, in *ListDriversRequest, opts ...grpc.CallOption) (*ListDriversResponse, error)
	// GetDriver resolves one driver by master-data id — the business service
	// reads the phone and the optional login when it assigns work.
	GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error)
	// GetTrucksByDriver supports the assign-driver flow in the business service,
	// which must know which trucks a driver is paired with.
	GetTrucksByDriver(ctx context.Context, in *GetTrucksByDriverRequest, opts ...grpc.CallOption) (*GetTrucksByDriverResponse, error)
	GetWarehouse(ctx context.Context, in *GetWarehouseRequest, opts ...grpc.CallOption) (*GetWarehouseResponse, error)
	ListWarehouses(ctx context.Context, in *ListWarehousesRequest, opts ...grpc.CallOption) (*ListWarehousesResponse, error)
}

type masterDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterDataServiceClient(cc grpc.ClientConnInterface) MasterDataServiceClient {
	return &masterDataServiceClient{cc}
}

func (c *masterDataServiceClient) GetCatalogItem(ctx context.Context, in *GetCatalogItemRequest, opts ...grpc.CallOption) (*GetCatalogItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogItemResponse)
	err := c.cc.Invoke(ctx, MasterDataService_GetCatalogItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) ListCatalogItems(ctx context.Context, in *ListCatalogItemsRequest, opts ...grpc.CallOption) (*ListCatalogItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatalogItemsResponse)
	err := c.cc.Invoke(ctx, MasterDataService_ListCatalogItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) ResolveCatalogItems(ctx context.Context, in *ResolveCatalogItemsRequest, opts ...grpc.CallOption) (*ResolveCatalogItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCatalogItemsResponse)
	err := c.cc.Invoke(ctx, MasterDataService_ResolveCatalogItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) ValidateReferences(ctx context.Context, in *ValidateReferencesRequest, opts ...grpc.CallOption) (*ValidateReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateReferencesResponse)
	err := c.cc.Invoke(ctx, MasterDataService_ValidateReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) GetTruck(ctx context.Context, in *GetTruckRequest, opts ...grpc.CallOption) (*GetTruckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTruckResponse)
	err := c.cc.Invoke(ctx, MasterDataService_GetTruck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) ListTrucks(ctx context.Context, in *ListTrucksRequest, opts ...grpc.CallOption) (*ListTrucksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrucksResponse)
	err := c.cc.Invoke(ctx, MasterDataService_ListTrucks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) ListDrivers(ctx context.Context, in *ListDriversRequest, opts ...grpc.CallOption) (*ListDriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriversResponse)
	err := c.cc.Invoke(ctx, MasterDataService_ListDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverResponse)
	err := c.cc.Invoke(ctx, MasterDataService_GetDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) GetTrucksByDriver(ctx context.Context, in *GetTrucksByDriverRequest, opts ...grpc.CallOption) (*GetTrucksByDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrucksByDriverResponse)
	err := c.cc.Invoke(ctx, MasterDataService_GetTrucksByDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) GetWarehouse(ctx context.Context, in *GetWarehouseRequest, opts ...grpc.CallOption) (*GetWarehouseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWarehouseResponse)
	err := c.cc.Invoke(ctx, MasterDataService_GetWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataServiceClient) ListWarehouses(ctx context.Context, in *ListWarehousesRequest, opts ...grpc.CallOption) (*ListWarehousesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWarehousesResponse)
	err := c.cc.Invoke(ctx, MasterDataService_ListWarehouses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterDataServiceServer is the server API for MasterDataService service.
// All implementations must embed UnimplementedMasterDataServiceServer
// for forward compatibility.
//
// MasterDataService owns reference data. It splits into two families:
//
//	Global catalogues  - truck types, cargo types, item types, provinces,
//	                     cities, currencies. Shared by every company, edited
//	                     by Karlo staff.
//	Company catalogues - trucks, truck groups, warehouses, customers, points,
//	                     saved routes. Owned by one company, edited by that
//	                     company.
//
// Both live in MongoDB because the shapes are heterogeneous and read-mostly.
type MasterDataServiceServer interface {
	// GetCatalogItem resolves one entry from a global catalogue.
	GetCatalogItem(context.Context, *GetCatalogItemRequest) (*GetCatalogItemResponse, error)
	// ListCatalogItems pages through a global catalogue.
	ListCatalogItems(context.Context, *ListCatalogItemsRequest) (*ListCatalogItemsResponse, error)
	// ResolveCatalogItems batch-resolves catalogue references so a caller can
	// denormalise many foreign keys in one round trip. Callers that render an
	// order list use this instead of one lookup per row.
	ResolveCatalogItems(context.Context, *ResolveCatalogItemsRequest) (*ResolveCatalogItemsResponse, error)
	// ValidateReferences checks that a set of catalogue references exists before
	// the business service commits a write. Returns the invalid ones.
	ValidateReferences(context.Context, *ValidateReferencesRequest) (*ValidateReferencesResponse, error)
	GetTruck(context.Context, *GetTruckRequest) (*GetTruckResponse, error)
	ListTrucks(context.Context, *ListTrucksRequest) (*ListTrucksResponse, error)
	// ListDrivers pages a company's driver register, for a service that keeps
	// a projection of it — FMS's driversync. updated_since makes it
	// incremental; deleted rows are included so a projection can retire them.
	ListDrivers(context.Context, *ListDriversRequest) (*ListDriversResponse, error)
	// GetDriver resolves one driver by master-data id — the business service
	// reads the phone and the optional login when it assigns work.
	GetDriver(context.Context, *GetDriverRequest) (*GetDriverResponse, error)
	// GetTrucksByDriver supports the assign-driver flow in the business service,
	// which must know which trucks a driver is paired with.
	GetTrucksByDriver(context.Context, *GetTrucksByDriverRequest) (*GetTrucksByDriverResponse, error)
	GetWarehouse(context.Context, *GetWarehouseRequest) (*GetWarehouseResponse, error)
	ListWarehouses(context.Context, *ListWarehousesRequest) (*ListWarehousesResponse, error)
	mustEmbedUnimplementedMasterDataServiceServer()
}

// UnimplementedMasterDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterDataServiceServer struct{}

func (UnimplementedMasterDataServiceServer) GetCatalogItem(context.Context, *GetCatalogItemRequest) (*GetCatalogItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatalogItem not implemented")
}
func (UnimplementedMasterDataServiceServer) ListCatalogItems(context.Context, *ListCatalogItemsRequest) (*ListCatalogItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCatalogItems not implemented")
}
func (UnimplementedMasterDataServiceServer) ResolveCatalogItems(context.Context, *ResolveCatalogItemsRequest) (*ResolveCatalogItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCatalogItems not implemented")
}
func (UnimplementedMasterDataServiceServer) ValidateReferences(context.Context, *ValidateReferencesRequest) (*ValidateReferencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateReferences not implemented")
}
func (UnimplementedMasterDataServiceServer) GetTruck(context.Context, *GetTruckRequest) (*GetTruckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTruck not implemented")
}
func (UnimplementedMasterDataServiceServer) ListTrucks(context.Context, *ListTrucksRequest) (*ListTrucksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrucks not implemented")
}
func (UnimplementedMasterDataServiceServer) ListDrivers(context.Context, *ListDriversRequest) (*ListDriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrivers not implemented")
}
func (UnimplementedMasterDataServiceServer) GetDriver(context.Context, *GetDriverRequest) (*GetDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriver not implemented")
}
func (UnimplementedMasterDataServiceServer) GetTrucksByDriver(context.Context, *GetTrucksByDriverRequest) (*GetTrucksByDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrucksByDriver not implemented")
}
func (UnimplementedMasterDataServiceServer) GetWarehouse(context.Context, *GetWarehouseRequest) (*GetWarehouseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWarehouse not implemented")
}
func (UnimplementedMasterDataServiceServer) ListWarehouses(context.Context, *ListWarehousesRequest) (*ListWarehousesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWarehouses not implemented")
}
func (UnimplementedMasterDataServiceServer) mustEmbedUnimplementedMasterDataServiceServer() {}
func (UnimplementedMasterDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMasterDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterDataServiceServer will
// result in compilation errors.
type UnsafeMasterDataServiceServer interface {
	mustEmbedUnimplementedMasterDataServiceServer()
}

func RegisterMasterDataServiceServer(s grpc.ServiceRegistrar, srv MasterDataServiceServer) {
	// If the following call panics, it indicates UnimplementedMasterDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterDataService_ServiceDesc, srv)
}

func _MasterDataService_GetCatalogItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).GetCatalogItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_GetCatalogItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).GetCatalogItem(ctx, req.(*GetCatalogItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_ListCatalogItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).ListCatalogItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_ListCatalogItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).ListCatalogItems(ctx, req.(*ListCatalogItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_ResolveCatalogItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCatalogItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).ResolveCatalogItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_ResolveCatalogItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).ResolveCatalogItems(ctx, req.(*ResolveCatalogItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_ValidateReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).ValidateReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_ValidateReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).ValidateReferences(ctx, req.(*ValidateReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_GetTruck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTruckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).GetTruck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_GetTruck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).GetTruck(ctx, req.(*GetTruckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_ListTrucks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrucksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).ListTrucks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_ListTrucks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).ListTrucks(ctx, req.(*ListTrucksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_ListDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).ListDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_ListDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).ListDrivers(ctx, req.(*ListDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_GetDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).GetDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_GetDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).GetDriver(ctx, req.(*GetDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_GetTrucksByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrucksByDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).GetTrucksByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_GetTrucksByDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).GetTrucksByDriver(ctx, req.(*GetTrucksByDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_GetWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).GetWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_GetWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).GetWarehouse(ctx, req.(*GetWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterDataService_ListWarehouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarehousesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).ListWarehouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterDataService_ListWarehouses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).ListWarehouses(ctx, req.(*ListWarehousesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterDataService_ServiceDesc is the grpc.ServiceDesc for MasterDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "karlo.masterdata.v1.MasterDataService",
	HandlerType: (*MasterDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatalogItem",
			Handler:    _MasterDataService_GetCatalogItem_Handler,
		},
		{
			MethodName: "ListCatalogItems",
			Handler:    _MasterDataService_ListCatalogItems_Handler,
		},
		{
			MethodName: "ResolveCatalogItems",
			Handler:    _MasterDataService_ResolveCatalogItems_Handler,
		},
		{
			MethodName: "ValidateReferences",
			Handler:    _MasterDataService_ValidateReferences_Handler,
		},
		{
			MethodName: "GetTruck",
			Handler:    _MasterDataService_GetTruck_Handler,
		},
		{
			MethodName: "ListTrucks",
			Handler:    _MasterDataService_ListTrucks_Handler,
		},
		{
			MethodName: "ListDrivers",
			Handler:    _MasterDataService_ListDrivers_Handler,
		},
		{
			MethodName: "GetDriver",
			Handler:    _MasterDataService_GetDriver_Handler,
		},
		{
			MethodName: "GetTrucksByDriver",
			Handler:    _MasterDataService_GetTrucksByDriver_Handler,
		},
		{
			MethodName: "GetWarehouse",
			Handler:    _MasterDataService_GetWarehouse_Handler,
		},
		{
			MethodName: "ListWarehouses",
			Handler:    _MasterDataService_ListWarehouses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "karlo/masterdata/v1/masterdata.proto",
}
