// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: karlo/notification/v1/notification.proto

package notificationv1

import (
	v1 "github.com/karlo/notification-service/internal/platform/genproto/karlo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel is a delivery mechanism.
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	// CHANNEL_IN_APP persists the notification for the inbox only.
	Channel_CHANNEL_IN_APP   Channel = 1
	Channel_CHANNEL_PUSH     Channel = 2
	Channel_CHANNEL_EMAIL    Channel = 3
	Channel_CHANNEL_WHATSAPP Channel = 4
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_IN_APP",
		2: "CHANNEL_PUSH",
		3: "CHANNEL_EMAIL",
		4: "CHANNEL_WHATSAPP",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_IN_APP":      1,
		"CHANNEL_PUSH":        2,
		"CHANNEL_EMAIL":       3,
		"CHANNEL_WHATSAPP":    4,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_karlo_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_karlo_notification_v1_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

// EventType identifies what happened. The service maps each event to a default
// channel set and a message template, which is why callers do not pass copy.
// The values mirror the `type` strings the legacy Notification model documented.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED                EventType = 0
	EventType_EVENT_TYPE_ORDER_CREATED              EventType = 1
	EventType_EVENT_TYPE_ORDER_UPDATED              EventType = 2
	EventType_EVENT_TYPE_ORDER_CANCELLED            EventType = 3
	EventType_EVENT_TYPE_ORDER_READY_TO_PLAN        EventType = 4
	EventType_EVENT_TYPE_ORDER_ASSIGNED_DRIVER      EventType = 5
	EventType_EVENT_TYPE_ORDER_REQUEST_DELIVERY     EventType = 6
	EventType_EVENT_TYPE_ORDER_APPROVAL_REQUIRED    EventType = 7
	EventType_EVENT_TYPE_AGREEMENT_CREATED          EventType = 8
	EventType_EVENT_TYPE_AGREEMENT_APPROVED         EventType = 9
	EventType_EVENT_TYPE_AGREEMENT_REJECTED         EventType = 10
	EventType_EVENT_TYPE_AGREEMENT_EXPIRED          EventType = 11
	EventType_EVENT_TYPE_SHIPMENT_STARTED           EventType = 12
	EventType_EVENT_TYPE_SHIPMENT_ARRIVED_LOADING   EventType = 13
	EventType_EVENT_TYPE_SHIPMENT_LOADED            EventType = 14
	EventType_EVENT_TYPE_SHIPMENT_ARRIVED_UNLOADING EventType = 15
	EventType_EVENT_TYPE_SHIPMENT_FINISHED          EventType = 16
	EventType_EVENT_TYPE_INVOICE_ISSUED             EventType = 17
	EventType_EVENT_TYPE_INVOICE_PAID               EventType = 18
	EventType_EVENT_TYPE_DRIVER_INVITED             EventType = 19
	EventType_EVENT_TYPE_COLLABORATION_INVITED      EventType = 20
	EventType_EVENT_TYPE_TRUCK_DRIVER_PAIRED        EventType = 21
	EventType_EVENT_TYPE_TASK_ASSIGNED              EventType = 22
	EventType_EVENT_TYPE_CHAT_MESSAGE               EventType = 23
	EventType_EVENT_TYPE_OTP                        EventType = 24
	// A planner registered a driver's K-Trip account: the driver gets the app
	// link and their credentials on WhatsApp. No in-app copy — there is no
	// inbox yet to put it in.
	EventType_EVENT_TYPE_DRIVER_ACCOUNT_CREATED EventType = 25
	// The driver flow. HANDOVER_CODE goes to the receiving PIC on WhatsApp with
	// the OTP and the Web-Field link; POD_SUBMITTED to the reviewers; the
	// review's outcome to the driver as a push.
	EventType_EVENT_TYPE_HANDOVER_CODE EventType = 26
	EventType_EVENT_TYPE_POD_SUBMITTED EventType = 27
	EventType_EVENT_TYPE_POD_APPROVED  EventType = 28
	EventType_EVENT_TYPE_POD_REJECTED  EventType = 29
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_ORDER_CREATED",
		2:  "EVENT_TYPE_ORDER_UPDATED",
		3:  "EVENT_TYPE_ORDER_CANCELLED",
		4:  "EVENT_TYPE_ORDER_READY_TO_PLAN",
		5:  "EVENT_TYPE_ORDER_ASSIGNED_DRIVER",
		6:  "EVENT_TYPE_ORDER_REQUEST_DELIVERY",
		7:  "EVENT_TYPE_ORDER_APPROVAL_REQUIRED",
		8:  "EVENT_TYPE_AGREEMENT_CREATED",
		9:  "EVENT_TYPE_AGREEMENT_APPROVED",
		10: "EVENT_TYPE_AGREEMENT_REJECTED",
		11: "EVENT_TYPE_AGREEMENT_EXPIRED",
		12: "EVENT_TYPE_SHIPMENT_STARTED",
		13: "EVENT_TYPE_SHIPMENT_ARRIVED_LOADING",
		14: "EVENT_TYPE_SHIPMENT_LOADED",
		15: "EVENT_TYPE_SHIPMENT_ARRIVED_UNLOADING",
		16: "EVENT_TYPE_SHIPMENT_FINISHED",
		17: "EVENT_TYPE_INVOICE_ISSUED",
		18: "EVENT_TYPE_INVOICE_PAID",
		19: "EVENT_TYPE_DRIVER_INVITED",
		20: "EVENT_TYPE_COLLABORATION_INVITED",
		21: "EVENT_TYPE_TRUCK_DRIVER_PAIRED",
		22: "EVENT_TYPE_TASK_ASSIGNED",
		23: "EVENT_TYPE_CHAT_MESSAGE",
		24: "EVENT_TYPE_OTP",
		25: "EVENT_TYPE_DRIVER_ACCOUNT_CREATED",
		26: "EVENT_TYPE_HANDOVER_CODE",
		27: "EVENT_TYPE_POD_SUBMITTED",
		28: "EVENT_TYPE_POD_APPROVED",
		29: "EVENT_TYPE_POD_REJECTED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":                0,
		"EVENT_TYPE_ORDER_CREATED":              1,
		"EVENT_TYPE_ORDER_UPDATED":              2,
		"EVENT_TYPE_ORDER_CANCELLED":            3,
		"EVENT_TYPE_ORDER_READY_TO_PLAN":        4,
		"EVENT_TYPE_ORDER_ASSIGNED_DRIVER":      5,
		"EVENT_TYPE_ORDER_REQUEST_DELIVERY":     6,
		"EVENT_TYPE_ORDER_APPROVAL_REQUIRED":    7,
		"EVENT_TYPE_AGREEMENT_CREATED":          8,
		"EVENT_TYPE_AGREEMENT_APPROVED":         9,
		"EVENT_TYPE_AGREEMENT_REJECTED":         10,
		"EVENT_TYPE_AGREEMENT_EXPIRED":          11,
		"EVENT_TYPE_SHIPMENT_STARTED":           12,
		"EVENT_TYPE_SHIPMENT_ARRIVED_LOADING":   13,
		"EVENT_TYPE_SHIPMENT_LOADED":            14,
		"EVENT_TYPE_SHIPMENT_ARRIVED_UNLOADING": 15,
		"EVENT_TYPE_SHIPMENT_FINISHED":          16,
		"EVENT_TYPE_INVOICE_ISSUED":             17,
		"EVENT_TYPE_INVOICE_PAID":               18,
		"EVENT_TYPE_DRIVER_INVITED":             19,
		"EVENT_TYPE_COLLABORATION_INVITED":      20,
		"EVENT_TYPE_TRUCK_DRIVER_PAIRED":        21,
		"EVENT_TYPE_TASK_ASSIGNED":              22,
		"EVENT_TYPE_CHAT_MESSAGE":               23,
		"EVENT_TYPE_OTP":                        24,
		"EVENT_TYPE_DRIVER_ACCOUNT_CREATED":     25,
		"EVENT_TYPE_HANDOVER_CODE":              26,
		"EVENT_TYPE_POD_SUBMITTED":              27,
		"EVENT_TYPE_POD_APPROVED":               28,
		"EVENT_TYPE_POD_REJECTED":               29,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_karlo_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_karlo_notification_v1_notification_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

// Audience states who should receive a notification. Exactly one field is set.
// Resolving a role or company audience is the notification service's job, done
// through the authentication service, so business logic never has to fetch user
// lists just to send a message.
type Audience struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*Audience_Users
	//	*Audience_CompanyRole
	//	*Audience_TruckGroup
	//	*Audience_Phone
	Target        isAudience_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audience) Reset() {
	*x = Audience{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audience) ProtoMessage() {}

func (x *Audience) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audience.ProtoReflect.Descriptor instead.
func (*Audience) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Audience) GetTarget() isAudience_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Audience) GetUsers() *UserList {
	if x != nil {
		if x, ok := x.Target.(*Audience_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *Audience) GetCompanyRole() *CompanyRole {
	if x != nil {
		if x, ok := x.Target.(*Audience_CompanyRole); ok {
			return x.CompanyRole
		}
	}
	return nil
}

func (x *Audience) GetTruckGroup() *TruckGroup {
	if x != nil {
		if x, ok := x.Target.(*Audience_TruckGroup); ok {
			return x.TruckGroup
		}
	}
	return nil
}

func (x *Audience) GetPhone() *PhoneNumber {
	if x != nil {
		if x, ok := x.Target.(*Audience_Phone); ok {
			return x.Phone
		}
	}
	return nil
}

type isAudience_Target interface {
	isAudience_Target()
}

type Audience_Users struct {
	Users *UserList `protobuf:"bytes,1,opt,name=users,proto3,oneof"`
}

type Audience_CompanyRole struct {
	CompanyRole *CompanyRole `protobuf:"bytes,2,opt,name=company_role,json=companyRole,proto3,oneof"`
}

type Audience_TruckGroup struct {
	TruckGroup *TruckGroup `protobuf:"bytes,3,opt,name=truck_group,json=truckGroup,proto3,oneof"`
}

type Audience_Phone struct {
	Phone *PhoneNumber `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*Audience_Users) isAudience_Target() {}

func (*Audience_CompanyRole) isAudience_Target() {}

func (*Audience_TruckGroup) isAudience_Target() {}

func (*Audience_Phone) isAudience_Target() {}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *UserList) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CompanyRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyRole) Reset() {
	*x = CompanyRole{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyRole) ProtoMessage() {}

func (x *CompanyRole) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyRole.ProtoReflect.Descriptor instead.
func (*CompanyRole) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *CompanyRole) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CompanyRole) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type TruckGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckGroupId  string                 `protobuf:"bytes,1,opt,name=truck_group_id,json=truckGroupId,proto3" json:"truck_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruckGroup) Reset() {
	*x = TruckGroup{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruckGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckGroup) ProtoMessage() {}

func (x *TruckGroup) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckGroup.ProtoReflect.Descriptor instead.
func (*TruckGroup) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *TruckGroup) GetTruckGroupId() string {
	if x != nil {
		return x.TruckGroupId
	}
	return ""
}

type PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type NotifyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Event    EventType              `protobuf:"varint,1,opt,name=event,proto3,enum=karlo.notification.v1.EventType" json:"event,omitempty"`
	Audience *Audience              `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	// subject_id is the id of the thing the event is about: the order, the
	// agreement, the invoice. It becomes the deep link target in the mobile app.
	SubjectId   string `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// params feed the message template. Templates are owned by this service, so
	// callers pass data, not prose.
	Params *structpb.Struct `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	// channels overrides the default channel set for the event. Leave empty to
	// accept the default.
	Channels []Channel `protobuf:"varint,6,rep,packed,name=channels,proto3,enum=karlo.notification.v1.Channel" json:"channels,omitempty"`
	// idempotency_key makes retries safe. A repeat within the dedupe window
	// returns the original notification instead of delivering twice.
	IdempotencyKey string `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// actor_id is the user who caused the event; they are excluded from the
	// audience so nobody is notified of their own action.
	ActorId       string `protobuf:"bytes,8,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyRequest) GetEvent() EventType {
	if x != nil {
		return x.Event
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *NotifyRequest) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *NotifyRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *NotifyRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *NotifyRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *NotifyRequest) GetChannels() []Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *NotifyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *NotifyRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type NotifyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// delivered reports per-channel outcomes. Delivery is best-effort: a push
	// failure does not fail the RPC, because the in-app record is the source of
	// truth.
	Delivered     []*ChannelResult `protobuf:"bytes,2,rep,name=delivered,proto3" json:"delivered,omitempty"`
	Deduplicated  bool             `protobuf:"varint,3,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotifyResponse) GetDelivered() []*ChannelResult {
	if x != nil {
		return x.Delivered
	}
	return nil
}

func (x *NotifyResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type ChannelResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Channel        Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=karlo.notification.v1.Channel" json:"channel,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RecipientCount int32                  `protobuf:"varint,3,opt,name=recipient_count,json=recipientCount,proto3" json:"recipient_count,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChannelResult) Reset() {
	*x = ChannelResult{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResult) ProtoMessage() {}

func (x *ChannelResult) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResult.ProtoReflect.Descriptor instead.
func (*ChannelResult) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelResult) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ChannelResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChannelResult) GetRecipientCount() int32 {
	if x != nil {
		return x.RecipientCount
	}
	return 0
}

func (x *ChannelResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NotifyBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotifyRequest       `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBatchRequest) Reset() {
	*x = NotifyBatchRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBatchRequest) ProtoMessage() {}

func (x *NotifyBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBatchRequest.ProtoReflect.Descriptor instead.
func (*NotifyBatchRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyBatchRequest) GetNotifications() []*NotifyRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type NotifyBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*NotifyResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBatchResponse) Reset() {
	*x = NotifyBatchResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBatchResponse) ProtoMessage() {}

func (x *NotifyBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBatchResponse.ProtoReflect.Descriptor instead.
func (*NotifyBatchResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyBatchResponse) GetResults() []*NotifyResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         EventType              `protobuf:"varint,2,opt,name=event,proto3,enum=karlo.notification.v1.EventType" json:"event,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SubjectId     string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType   string                 `protobuf:"bytes,6,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,8,opt,name=params,proto3" json:"params,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetEvent() EventType {
	if x != nil {
		return x.Event
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Notification) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Notification) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         *v1.Query              `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	UnreadOnly    bool                   `protobuf:"varint,3,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotificationsRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type CountUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountUnreadRequest) Reset() {
	*x = CountUnreadRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUnreadRequest) ProtoMessage() {}

func (x *CountUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUnreadRequest.ProtoReflect.Descriptor instead.
func (*CountUnreadRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{13}
}

func (x *CountUnreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CountUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountUnreadResponse) Reset() {
	*x = CountUnreadResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUnreadResponse) ProtoMessage() {}

func (x *CountUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUnreadResponse.ProtoReflect.Descriptor instead.
func (*CountUnreadResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{14}
}

func (x *CountUnreadResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarkReadRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// notification_ids empty together with all=true marks the whole inbox.
	NotificationIds []string `protobuf:"bytes,2,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"`
	All             bool     `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{15}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

func (x *MarkReadRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       int64                  `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{16}
}

func (x *MarkReadResponse) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type SendOtpRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// purpose distinguishes registration, login and phone-change flows so codes
	// issued for one cannot be spent on another.
	Purpose       string `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Language      string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpRequest) Reset() {
	*x = SendOtpRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpRequest) ProtoMessage() {}

func (x *SendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpRequest.ProtoReflect.Descriptor instead.
func (*SendOtpRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{17}
}

func (x *SendOtpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SendOtpRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SendOtpRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendOtpResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sent      bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// retry_after_seconds is set when the request was rate limited.
	RetryAfterSeconds int32 `protobuf:"varint,3,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendOtpResponse) Reset() {
	*x = SendOtpResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpResponse) ProtoMessage() {}

func (x *SendOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpResponse.ProtoReflect.Descriptor instead.
func (*SendOtpResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{18}
}

func (x *SendOtpResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *SendOtpResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SendOtpResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type VerifyOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOtpRequest) Reset() {
	*x = VerifyOtpRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRequest) ProtoMessage() {}

func (x *VerifyOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyOtpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *VerifyOtpRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyOtpRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type VerifyOtpResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Verified bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Reason   string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// attempts_remaining lets the caller show a useful error before lockout.
	AttemptsRemaining int32 `protobuf:"varint,3,opt,name=attempts_remaining,json=attemptsRemaining,proto3" json:"attempts_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyOtpResponse) Reset() {
	*x = VerifyOtpResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpResponse) ProtoMessage() {}

func (x *VerifyOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpResponse.ProtoReflect.Descriptor instead.
func (*VerifyOtpResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyOtpResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyOtpResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VerifyOtpResponse) GetAttemptsRemaining() int32 {
	if x != nil {
		return x.AttemptsRemaining
	}
	return 0
}

type EmailAttachment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Filename    string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content     []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// url is an alternative to inline content for large documents already in S3.
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAttachment) Reset() {
	*x = EmailAttachment{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAttachment) ProtoMessage() {}

func (x *EmailAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAttachment.ProtoReflect.Descriptor instead.
func (*EmailAttachment) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{21}
}

func (x *EmailAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EmailAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EmailAttachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *EmailAttachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SendDocumentEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	To    []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc    []string               `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	// template names a template owned by this service, e.g. "invoice_issued".
	Template      string             `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Params        *structpb.Struct   `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Attachments   []*EmailAttachment `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Language      string             `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentEmailRequest) Reset() {
	*x = SendDocumentEmailRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentEmailRequest) ProtoMessage() {}

func (x *SendDocumentEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentEmailRequest.ProtoReflect.Descriptor instead.
func (*SendDocumentEmailRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{22}
}

func (x *SendDocumentEmailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendDocumentEmailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendDocumentEmailRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SendDocumentEmailRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SendDocumentEmailRequest) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendDocumentEmailRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendDocumentEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentEmailResponse) Reset() {
	*x = SendDocumentEmailResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentEmailResponse) ProtoMessage() {}

func (x *SendDocumentEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentEmailResponse.ProtoReflect.Descriptor instead.
func (*SendDocumentEmailResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{23}
}

func (x *SendDocumentEmailResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *SendDocumentEmailResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendDocumentEmailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PushToken     string                 `protobuf:"bytes,2,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenRequest) Reset() {
	*x = RegisterDeviceTokenRequest{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenRequest) ProtoMessage() {}

func (x *RegisterDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{24}
}

func (x *RegisterDeviceTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RegisterDeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenResponse) Reset() {
	*x = RegisterDeviceTokenResponse{}
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenResponse) ProtoMessage() {}

func (x *RegisterDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_notification_v1_notification_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_karlo_notification_v1_notification_proto_rawDescGZIP(), []int{25}
}

func (x *RegisterDeviceTokenResponse) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

var File_karlo_notification_v1_notification_proto protoreflect.FileDescriptor

const file_karlo_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"(karlo/notification/v1/notification.proto\x12\x15karlo.notification.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ckarlo/common/v1/common.proto\"\x98\x02\n" +
	"\bAudience\x127\n" +
	"\x05users\x18\x01 \x01(\v2\x1f.karlo.notification.v1.UserListH\x00R\x05users\x12G\n" +
	"\fcompany_role\x18\x02 \x01(\v2\".karlo.notification.v1.CompanyRoleH\x00R\vcompanyRole\x12D\n" +
	"\vtruck_group\x18\x03 \x01(\v2!.karlo.notification.v1.TruckGroupH\x00R\n" +
	"truckGroup\x12:\n" +
	"\x05phone\x18\x04 \x01(\v2\".karlo.notification.v1.PhoneNumberH\x00R\x05phoneB\b\n" +
	"\x06target\"%\n" +
	"\bUserList\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"B\n" +
	"\vCompanyRole\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"2\n" +
	"\n" +
	"TruckGroup\x12$\n" +
	"\x0etruck_group_id\x18\x01 \x01(\tR\ftruckGroupId\"%\n" +
	"\vPhoneNumber\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\"\xf7\x02\n" +
	"\rNotifyRequest\x126\n" +
	"\x05event\x18\x01 \x01(\x0e2 .karlo.notification.v1.EventTypeR\x05event\x12;\n" +
	"\baudience\x18\x02 \x01(\v2\x1f.karlo.notification.v1.AudienceR\baudience\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12/\n" +
	"\x06params\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06params\x12:\n" +
	"\bchannels\x18\x06 \x03(\x0e2\x1e.karlo.notification.v1.ChannelR\bchannels\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\bactor_id\x18\b \x01(\tR\aactorId\"\xa1\x01\n" +
	"\x0eNotifyResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12B\n" +
	"\tdelivered\x18\x02 \x03(\v2$.karlo.notification.v1.ChannelResultR\tdelivered\x12\"\n" +
	"\fdeduplicated\x18\x03 \x01(\bR\fdeduplicated\"\xa2\x01\n" +
	"\rChannelResult\x128\n" +
	"\achannel\x18\x01 \x01(\x0e2\x1e.karlo.notification.v1.ChannelR\achannel\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12'\n" +
	"\x0frecipient_count\x18\x03 \x01(\x05R\x0erecipientCount\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"`\n" +
	"\x12NotifyBatchRequest\x12J\n" +
	"\rnotifications\x18\x01 \x03(\v2$.karlo.notification.v1.NotifyRequestR\rnotifications\"V\n" +
	"\x13NotifyBatchResponse\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.karlo.notification.v1.NotifyResponseR\aresults\"\xd0\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x05event\x18\x02 \x01(\x0e2 .karlo.notification.v1.EventTypeR\x05event\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x06 \x01(\tR\vsubjectType\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x12/\n" +
	"\x06params\x18\b \x01(\v2\x17.google.protobuf.StructR\x06params\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x01\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.karlo.common.v1.QueryR\x05query\x12\x1f\n" +
	"\vunread_only\x18\x03 \x01(\bR\n" +
	"unreadOnly\"\x9e\x01\n" +
	"\x19ListNotificationsResponse\x12I\n" +
	"\rnotifications\x18\x01 \x03(\v2#.karlo.notification.v1.NotificationR\rnotifications\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.karlo.common.v1.PageInfoR\bpageInfo\"-\n" +
	"\x12CountUnreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x13CountUnreadResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"g\n" +
	"\x0fMarkReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10notification_ids\x18\x02 \x03(\tR\x0fnotificationIds\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\",\n" +
	"\x10MarkReadResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\x03R\aupdated\"i\n" +
	"\x0eSendOtpRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\x90\x01\n" +
	"\x0fSendOtpResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12.\n" +
	"\x13retry_after_seconds\x18\x03 \x01(\x05R\x11retryAfterSeconds\"c\n" +
	"\x10VerifyOtpRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\"v\n" +
	"\x11VerifyOtpResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x12attempts_remaining\x18\x03 \x01(\x05R\x11attemptsRemaining\"|\n" +
	"\x0fEmailAttachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\xed\x01\n" +
	"\x18SendDocumentEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x02 \x03(\tR\x02cc\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\x12H\n" +
	"\vattachments\x18\x05 \x03(\v2&.karlo.notification.v1.EmailAttachmentR\vattachments\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\"d\n" +
	"\x19SendDocumentEmailResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x1aRegisterDeviceTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"push_token\x18\x02 \x01(\tR\tpushToken\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"=\n" +
	"\x1bRegisterDeviceTokenResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered*q\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCHANNEL_IN_APP\x10\x01\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x02\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x03\x12\x14\n" +
	"\x10CHANNEL_WHATSAPP\x10\x04*\xee\a\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_ORDER_CREATED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_ORDER_UPDATED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_ORDER_CANCELLED\x10\x03\x12\"\n" +
	"\x1eEVENT_TYPE_ORDER_READY_TO_PLAN\x10\x04\x12$\n" +
	" EVENT_TYPE_ORDER_ASSIGNED_DRIVER\x10\x05\x12%\n" +
	"!EVENT_TYPE_ORDER_REQUEST_DELIVERY\x10\x06\x12&\n" +
	"\"EVENT_TYPE_ORDER_APPROVAL_REQUIRED\x10\a\x12 \n" +
	"\x1cEVENT_TYPE_AGREEMENT_CREATED\x10\b\x12!\n" +
	"\x1dEVENT_TYPE_AGREEMENT_APPROVED\x10\t\x12!\n" +
	"\x1dEVENT_TYPE_AGREEMENT_REJECTED\x10\n" +
	"\x12 \n" +
	"\x1cEVENT_TYPE_AGREEMENT_EXPIRED\x10\v\x12\x1f\n" +
	"\x1bEVENT_TYPE_SHIPMENT_STARTED\x10\f\x12'\n" +
	"#EVENT_TYPE_SHIPMENT_ARRIVED_LOADING\x10\r\x12\x1e\n" +
	"\x1aEVENT_TYPE_SHIPMENT_LOADED\x10\x0e\x12)\n" +
	"%EVENT_TYPE_SHIPMENT_ARRIVED_UNLOADING\x10\x0f\x12 \n" +
	"\x1cEVENT_TYPE_SHIPMENT_FINISHED\x10\x10\x12\x1d\n" +
	"\x19EVENT_TYPE_INVOICE_ISSUED\x10\x11\x12\x1b\n" +
	"\x17EVENT_TYPE_INVOICE_PAID\x10\x12\x12\x1d\n" +
	"\x19EVENT_TYPE_DRIVER_INVITED\x10\x13\x12$\n" +
	" EVENT_TYPE_COLLABORATION_INVITED\x10\x14\x12\"\n" +
	"\x1eEVENT_TYPE_TRUCK_DRIVER_PAIRED\x10\x15\x12\x1c\n" +
	"\x18EVENT_TYPE_TASK_ASSIGNED\x10\x16\x12\x1b\n" +
	"\x17EVENT_TYPE_CHAT_MESSAGE\x10\x17\x12\x12\n" +
	"\x0eEVENT_TYPE_OTP\x10\x18\x12%\n" +
	"!EVENT_TYPE_DRIVER_ACCOUNT_CREATED\x10\x19\x12\x1c\n" +
	"\x18EVENT_TYPE_HANDOVER_CODE\x10\x1a\x12\x1c\n" +
	"\x18EVENT_TYPE_POD_SUBMITTED\x10\x1b\x12\x1b\n" +
	"\x17EVENT_TYPE_POD_APPROVED\x10\x1c\x12\x1b\n" +
	"\x17EVENT_TYPE_POD_REJECTED\x10\x1d2\xbd\a\n" +
	"\x13NotificationService\x12U\n" +
	"\x06Notify\x12$.karlo.notification.v1.NotifyRequest\x1a%.karlo.notification.v1.NotifyResponse\x12d\n" +
	"\vNotifyBatch\x12).karlo.notification.v1.NotifyBatchRequest\x1a*.karlo.notification.v1.NotifyBatchResponse\x12v\n" +
	"\x11ListNotifications\x12/.karlo.notification.v1.ListNotificationsRequest\x1a0.karlo.notification.v1.ListNotificationsResponse\x12d\n" +
	"\vCountUnread\x12).karlo.notification.v1.CountUnreadRequest\x1a*.karlo.notification.v1.CountUnreadResponse\x12[\n" +
	"\bMarkRead\x12&.karlo.notification.v1.MarkReadRequest\x1a'.karlo.notification.v1.MarkReadResponse\x12X\n" +
	"\aSendOtp\x12%.karlo.notification.v1.SendOtpRequest\x1a&.karlo.notification.v1.SendOtpResponse\x12^\n" +
	"\tVerifyOtp\x12'.karlo.notification.v1.VerifyOtpRequest\x1a(.karlo.notification.v1.VerifyOtpResponse\x12v\n" +
	"\x11SendDocumentEmail\x12/.karlo.notification.v1.SendDocumentEmailRequest\x1a0.karlo.notification.v1.SendDocumentEmailResponse\x12|\n" +
	"\x13RegisterDeviceToken\x121.karlo.notification.v1.RegisterDeviceTokenRequest\x1a2.karlo.notification.v1.RegisterDeviceTokenResponseB\x8b\x02\n" +
	"\x19com.karlo.notification.v1B\x11NotificationProtoP\x01Zegithub.com/karlo/notification-service/internal/platform/genproto/karlo/notification/v1;notificationv1\xa2\x02\x03KNX\xaa\x02\x15Karlo.Notification.V1\xca\x02\x15Karlo\\Notification\\V1\xe2\x02!Karlo\\Notification\\V1\\GPBMetadata\xea\x02\x17Karlo::Notification::V1b\x06proto3"

var (
	file_karlo_notification_v1_notification_proto_rawDescOnce sync.Once
	file_karlo_notification_v1_notification_proto_rawDescData []byte
)

func file_karlo_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_karlo_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_karlo_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_karlo_notification_v1_notification_proto_rawDesc), len(file_karlo_notification_v1_notification_proto_rawDesc)))
	})
	return file_karlo_notification_v1_notification_proto_rawDescData
}

var file_karlo_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_karlo_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_karlo_notification_v1_notification_proto_goTypes = []any{
	(Channel)(0),                        // 0: karlo.notification.v1.Channel
	(EventType)(0),                      // 1: karlo.notification.v1.EventType
	(*Audience)(nil),                    // 2: karlo.notification.v1.Audience
	(*UserList)(nil),                    // 3: karlo.notification.v1.UserList
	(*CompanyRole)(nil),                 // 4: karlo.notification.v1.CompanyRole
	(*TruckGroup)(nil),                  // 5: karlo.notification.v1.TruckGroup
	(*PhoneNumber)(nil),                 // 6: karlo.notification.v1.PhoneNumber
	(*NotifyRequest)(nil),               // 7: karlo.notification.v1.NotifyRequest
	(*NotifyResponse)(nil),              // 8: karlo.notification.v1.NotifyResponse
	(*ChannelResult)(nil),               // 9: karlo.notification.v1.ChannelResult
	(*NotifyBatchRequest)(nil),          // 10: karlo.notification.v1.NotifyBatchRequest
	(*NotifyBatchResponse)(nil),         // 11: karlo.notification.v1.NotifyBatchResponse
	(*Notification)(nil),                // 12: karlo.notification.v1.Notification
	(*ListNotificationsRequest)(nil),    // 13: karlo.notification.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),   // 14: karlo.notification.v1.ListNotificationsResponse
	(*CountUnreadRequest)(nil),          // 15: karlo.notification.v1.CountUnreadRequest
	(*CountUnreadResponse)(nil),         // 16: karlo.notification.v1.CountUnreadResponse
	(*MarkReadRequest)(nil),             // 17: karlo.notification.v1.MarkReadRequest
	(*MarkReadResponse)(nil),            // 18: karlo.notification.v1.MarkReadResponse
	(*SendOtpRequest)(nil),              // 19: karlo.notification.v1.SendOtpRequest
	(*SendOtpResponse)(nil),             // 20: karlo.notification.v1.SendOtpResponse
	(*VerifyOtpRequest)(nil),            // 21: karlo.notification.v1.VerifyOtpRequest
	(*VerifyOtpResponse)(nil),           // 22: karlo.notification.v1.VerifyOtpResponse
	(*EmailAttachment)(nil),             // 23: karlo.notification.v1.EmailAttachment
	(*SendDocumentEmailRequest)(nil),    // 24: karlo.notification.v1.SendDocumentEmailRequest
	(*SendDocumentEmailResponse)(nil),   // 25: karlo.notification.v1.SendDocumentEmailResponse
	(*RegisterDeviceTokenRequest)(nil),  // 26: karlo.notification.v1.RegisterDeviceTokenRequest
	(*RegisterDeviceTokenResponse)(nil), // 27: karlo.notification.v1.RegisterDeviceTokenResponse
	(*structpb.Struct)(nil),             // 28: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 29: google.protobuf.Timestamp
	(*v1.Query)(nil),                    // 30: karlo.common.v1.Query
	(*v1.PageInfo)(nil),                 // 31: karlo.common.v1.PageInfo
}
var file_karlo_notification_v1_notification_proto_depIdxs = []int32{
	3,  // 0: karlo.notification.v1.Audience.users:type_name -> karlo.notification.v1.UserList
	4,  // 1: karlo.notification.v1.Audience.company_role:type_name -> karlo.notification.v1.CompanyRole
	5,  // 2: karlo.notification.v1.Audience.truck_group:type_name -> karlo.notification.v1.TruckGroup
	6,  // 3: karlo.notification.v1.Audience.phone:type_name -> karlo.notification.v1.PhoneNumber
	1,  // 4: karlo.notification.v1.NotifyRequest.event:type_name -> karlo.notification.v1.EventType
	2,  // 5: karlo.notification.v1.NotifyRequest.audience:type_name -> karlo.notification.v1.Audience
	28, // 6: karlo.notification.v1.NotifyRequest.params:type_name -> google.protobuf.Struct
	0,  // 7: karlo.notification.v1.NotifyRequest.channels:type_name -> karlo.notification.v1.Channel
	9,  // 8: karlo.notification.v1.NotifyResponse.delivered:type_name -> karlo.notification.v1.ChannelResult
	0,  // 9: karlo.notification.v1.ChannelResult.channel:type_name -> karlo.notification.v1.Channel
	7,  // 10: karlo.notification.v1.NotifyBatchRequest.notifications:type_name -> karlo.notification.v1.NotifyRequest
	8,  // 11: karlo.notification.v1.NotifyBatchResponse.results:type_name -> karlo.notification.v1.NotifyResponse
	1,  // 12: karlo.notification.v1.Notification.event:type_name -> karlo.notification.v1.EventType
	28, // 13: karlo.notification.v1.Notification.params:type_name -> google.protobuf.Struct
	29, // 14: karlo.notification.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	30, // 15: karlo.notification.v1.ListNotificationsRequest.query:type_name -> karlo.common.v1.Query
	12, // 16: karlo.notification.v1.ListNotificationsResponse.notifications:type_name -> karlo.notification.v1.Notification
	31, // 17: karlo.notification.v1.ListNotificationsResponse.page_info:type_name -> karlo.common.v1.PageInfo
	29, // 18: karlo.notification.v1.SendOtpResponse.expires_at:type_name -> google.protobuf.Timestamp
	28, // 19: karlo.notification.v1.SendDocumentEmailRequest.params:type_name -> google.protobuf.Struct
	23, // 20: karlo.notification.v1.SendDocumentEmailRequest.attachments:type_name -> karlo.notification.v1.EmailAttachment
	7,  // 21: karlo.notification.v1.NotificationService.Notify:input_type -> karlo.notification.v1.NotifyRequest
	10, // 22: karlo.notification.v1.NotificationService.NotifyBatch:input_type -> karlo.notification.v1.NotifyBatchRequest
	13, // 23: karlo.notification.v1.NotificationService.ListNotifications:input_type -> karlo.notification.v1.ListNotificationsRequest
	15, // 24: karlo.notification.v1.NotificationService.CountUnread:input_type -> karlo.notification.v1.CountUnreadRequest
	17, // 25: karlo.notification.v1.NotificationService.MarkRead:input_type -> karlo.notification.v1.MarkReadRequest
	19, // 26: karlo.notification.v1.NotificationService.SendOtp:input_type -> karlo.notification.v1.SendOtpRequest
	21, // 27: karlo.notification.v1.NotificationService.VerifyOtp:input_type -> karlo.notification.v1.VerifyOtpRequest
	24, // 28: karlo.notification.v1.NotificationService.SendDocumentEmail:input_type -> karlo.notification.v1.SendDocumentEmailRequest
	26, // 29: karlo.notification.v1.NotificationService.RegisterDeviceToken:input_type -> karlo.notification.v1.RegisterDeviceTokenRequest
	8,  // 30: karlo.notification.v1.NotificationService.Notify:output_type -> karlo.notification.v1.NotifyResponse
	11, // 31: karlo.notification.v1.NotificationService.NotifyBatch:output_type -> karlo.notification.v1.NotifyBatchResponse
	14, // 32: karlo.notification.v1.NotificationService.ListNotifications:output_type -> karlo.notification.v1.ListNotificationsResponse
	16, // 33: karlo.notification.v1.NotificationService.CountUnread:output_type -> karlo.notification.v1.CountUnreadResponse
	18, // 34: karlo.notification.v1.NotificationService.MarkRead:output_type -> karlo.notification.v1.MarkReadResponse
	20, // 35: karlo.notification.v1.NotificationService.SendOtp:output_type -> karlo.notification.v1.SendOtpResponse
	22, // 36: karlo.notification.v1.NotificationService.VerifyOtp:output_type -> karlo.notification.v1.VerifyOtpResponse
	25, // 37: karlo.notification.v1.NotificationService.SendDocumentEmail:output_type -> karlo.notification.v1.SendDocumentEmailResponse
	27, // 38: karlo.notification.v1.NotificationService.RegisterDeviceToken:output_type -> karlo.notification.v1.RegisterDeviceTokenResponse
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_karlo_notification_v1_notification_proto_init() }
func file_karlo_notification_v1_notification_proto_init() {
	if File_karlo_notification_v1_notification_proto != nil {
		return
	}
	file_karlo_notification_v1_notification_proto_msgTypes[0].OneofWrappers = []any{
		(*Audience_Users)(nil),
		(*Audience_CompanyRole)(nil),
		(*Audience_TruckGroup)(nil),
		(*Audience_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_karlo_notification_v1_notification_proto_rawDesc), len(file_karlo_notification_v1_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_karlo_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_karlo_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_karlo_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_karlo_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_karlo_notification_v1_notification_proto = out.File
	file_karlo_notification_v1_notification_proto_goTypes = nil
	file_karlo_notification_v1_notification_proto_depIdxs = nil
}
