// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: karlo/notification/v1/notification.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_Notify_FullMethodName              = "/karlo.notification.v1.NotificationService/Notify"
	NotificationService_NotifyBatch_FullMethodName         = "/karlo.notification.v1.NotificationService/NotifyBatch"
	NotificationService_ListNotifications_FullMethodName   = "/karlo.notification.v1.NotificationService/ListNotifications"
	NotificationService_CountUnread_FullMethodName         = "/karlo.notification.v1.NotificationService/CountUnread"
	NotificationService_MarkRead_FullMethodName            = "/karlo.notification.v1.NotificationService/MarkRead"
	NotificationService_SendOtp_FullMethodName             = "/karlo.notification.v1.NotificationService/SendOtp"
	NotificationService_VerifyOtp_FullMethodName           = "/karlo.notification.v1.NotificationService/VerifyOtp"
	NotificationService_SendDocumentEmail_FullMethodName   = "/karlo.notification.v1.NotificationService/SendDocumentEmail"
	NotificationService_RegisterDeviceToken_FullMethodName = "/karlo.notification.v1.NotificationService/RegisterDeviceToken"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NotificationService is the single outbound-messaging boundary.
//
// It absorbs four things that were previously separate in the monolith:
//
//  1. The Notification mongo model in karlo_be / karlo_order, whose
//     post('save') hook fanned out to FCM. 70 creation sites in karlo_be and
//     47 in karlo_order now become Notify calls.
//  2. The Message / MessageGroup / MessageTemplate in-app chat, which had its
//     own independent FCM hook.
//  3. The nodemailer email sender, called directly from five controllers.
//  4. The WhatsApp Cloud API, OTP and support-ticket features of
//     communication-service-be.
//
// The key design point: a caller states WHO to reach and WHAT happened. This
// service decides WHICH channels to use, renders the template, and delivers.
// Callers never name FCM, SMTP or WhatsApp.
type NotificationServiceClient interface {
	// Notify records a notification and delivers it on every channel the event
	// type and the recipient's preferences call for. This is the RPC that the
	// ~117 legacy Notification.create sites map onto.
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// NotifyBatch delivers several unrelated notifications in one round trip.
	// Bulk order flows use it to avoid a call per row.
	NotifyBatch(ctx context.Context, in *NotifyBatchRequest, opts ...grpc.CallOption) (*NotifyBatchResponse, error)
	// ListNotifications serves a user's in-app notification inbox.
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	// CountUnread backs the badge count.
	CountUnread(ctx context.Context, in *CountUnreadRequest, opts ...grpc.CallOption) (*CountUnreadResponse, error)
	// MarkRead marks specific notifications, or a user's whole inbox, as read.
	MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	// SendOtp issues and delivers a one-time password over WhatsApp.
	SendOtp(ctx context.Context, in *SendOtpRequest, opts ...grpc.CallOption) (*SendOtpResponse, error)
	// VerifyOtp checks a code and consumes it.
	VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*VerifyOtpResponse, error)
	// SendDocumentEmail delivers a rendered document (invoice, POD, order
	// confirmation) as mail with attachments. This replaces the direct
	// nodemailer calls that were scattered through the order and shipment
	// controllers.
	SendDocumentEmail(ctx context.Context, in *SendDocumentEmailRequest, opts ...grpc.CallOption) (*SendDocumentEmailResponse, error)
	// RegisterDeviceToken records a device's push token. The token itself is
	// stored by the authentication service; this RPC forwards it there and keeps
	// the delivery-side device record.
	RegisterDeviceToken(ctx context.Context, in *RegisterDeviceTokenRequest, opts ...grpc.CallOption) (*RegisterDeviceTokenResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, NotificationService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotifyBatch(ctx context.Context, in *NotifyBatchRequest, opts ...grpc.CallOption) (*NotifyBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyBatchResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotifyBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CountUnread(ctx context.Context, in *CountUnreadRequest, opts ...grpc.CallOption) (*CountUnreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountUnreadResponse)
	err := c.cc.Invoke(ctx, NotificationService_CountUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendOtp(ctx context.Context, in *SendOtpRequest, opts ...grpc.CallOption) (*SendOtpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendOtpResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*VerifyOtpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOtpResponse)
	err := c.cc.Invoke(ctx, NotificationService_VerifyOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendDocumentEmail(ctx context.Context, in *SendDocumentEmailRequest, opts ...grpc.CallOption) (*SendDocumentEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDocumentEmailResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendDocumentEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) RegisterDeviceToken(ctx context.Context, in *RegisterDeviceTokenRequest, opts ...grpc.CallOption) (*RegisterDeviceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceTokenResponse)
	err := c.cc.Invoke(ctx, NotificationService_RegisterDeviceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
//
// NotificationService is the single outbound-messaging boundary.
//
// It absorbs four things that were previously separate in the monolith:
//
//  1. The Notification mongo model in karlo_be / karlo_order, whose
//     post('save') hook fanned out to FCM. 70 creation sites in karlo_be and
//     47 in karlo_order now become Notify calls.
//  2. The Message / MessageGroup / MessageTemplate in-app chat, which had its
//     own independent FCM hook.
//  3. The nodemailer email sender, called directly from five controllers.
//  4. The WhatsApp Cloud API, OTP and support-ticket features of
//     communication-service-be.
//
// The key design point: a caller states WHO to reach and WHAT happened. This
// service decides WHICH channels to use, renders the template, and delivers.
// Callers never name FCM, SMTP or WhatsApp.
type NotificationServiceServer interface {
	// Notify records a notification and delivers it on every channel the event
	// type and the recipient's preferences call for. This is the RPC that the
	// ~117 legacy Notification.create sites map onto.
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// NotifyBatch delivers several unrelated notifications in one round trip.
	// Bulk order flows use it to avoid a call per row.
	NotifyBatch(context.Context, *NotifyBatchRequest) (*NotifyBatchResponse, error)
	// ListNotifications serves a user's in-app notification inbox.
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	// CountUnread backs the badge count.
	CountUnread(context.Context, *CountUnreadRequest) (*CountUnreadResponse, error)
	// MarkRead marks specific notifications, or a user's whole inbox, as read.
	MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error)
	// SendOtp issues and delivers a one-time password over WhatsApp.
	SendOtp(context.Context, *SendOtpRequest) (*SendOtpResponse, error)
	// VerifyOtp checks a code and consumes it.
	VerifyOtp(context.Context, *VerifyOtpRequest) (*VerifyOtpResponse, error)
	// SendDocumentEmail delivers a rendered document (invoice, POD, order
	// confirmation) as mail with attachments. This replaces the direct
	// nodemailer calls that were scattered through the order and shipment
	// controllers.
	SendDocumentEmail(context.Context, *SendDocumentEmailRequest) (*SendDocumentEmailResponse, error)
	// RegisterDeviceToken records a device's push token. The token itself is
	// stored by the authentication service; this RPC forwards it there and keeps
	// the delivery-side device record.
	RegisterDeviceToken(context.Context, *RegisterDeviceTokenRequest) (*RegisterDeviceTokenResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedNotificationServiceServer) NotifyBatch(context.Context, *NotifyBatchRequest) (*NotifyBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyBatch not implemented")
}
func (UnimplementedNotificationServiceServer) ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) CountUnread(context.Context, *CountUnreadRequest) (*CountUnreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountUnread not implemented")
}
func (UnimplementedNotificationServiceServer) MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedNotificationServiceServer) SendOtp(context.Context, *SendOtpRequest) (*SendOtpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendOtp not implemented")
}
func (UnimplementedNotificationServiceServer) VerifyOtp(context.Context, *VerifyOtpRequest) (*VerifyOtpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOtp not implemented")
}
func (UnimplementedNotificationServiceServer) SendDocumentEmail(context.Context, *SendDocumentEmailRequest) (*SendDocumentEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDocumentEmail not implemented")
}
func (UnimplementedNotificationServiceServer) RegisterDeviceToken(context.Context, *RegisterDeviceTokenRequest) (*RegisterDeviceTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDeviceToken not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotifyBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotifyBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyBatch(ctx, req.(*NotifyBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CountUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CountUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CountUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CountUnread(ctx, req.(*CountUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendOtp(ctx, req.(*SendOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_VerifyOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).VerifyOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_VerifyOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).VerifyOtp(ctx, req.(*VerifyOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendDocumentEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDocumentEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendDocumentEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendDocumentEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendDocumentEmail(ctx, req.(*SendDocumentEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_RegisterDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).RegisterDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_RegisterDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).RegisterDeviceToken(ctx, req.(*RegisterDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "karlo.notification.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _NotificationService_Notify_Handler,
		},
		{
			MethodName: "NotifyBatch",
			Handler:    _NotificationService_NotifyBatch_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _NotificationService_ListNotifications_Handler,
		},
		{
			MethodName: "CountUnread",
			Handler:    _NotificationService_CountUnread_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _NotificationService_MarkRead_Handler,
		},
		{
			MethodName: "SendOtp",
			Handler:    _NotificationService_SendOtp_Handler,
		},
		{
			MethodName: "VerifyOtp",
			Handler:    _NotificationService_VerifyOtp_Handler,
		},
		{
			MethodName: "SendDocumentEmail",
			Handler:    _NotificationService_SendDocumentEmail_Handler,
		},
		{
			MethodName: "RegisterDeviceToken",
			Handler:    _NotificationService_RegisterDeviceToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "karlo/notification/v1/notification.proto",
}
