// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: karlo/auth/v1/auth.proto

package authv1

import (
	v1 "github.com/karlo/notification-service/internal/platform/genproto/karlo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenKind int32

const (
	TokenKind_TOKEN_KIND_UNSPECIFIED TokenKind = 0
	TokenKind_TOKEN_KIND_JWT         TokenKind = 1
	TokenKind_TOKEN_KIND_STATIC      TokenKind = 2
)

// Enum value maps for TokenKind.
var (
	TokenKind_name = map[int32]string{
		0: "TOKEN_KIND_UNSPECIFIED",
		1: "TOKEN_KIND_JWT",
		2: "TOKEN_KIND_STATIC",
	}
	TokenKind_value = map[string]int32{
		"TOKEN_KIND_UNSPECIFIED": 0,
		"TOKEN_KIND_JWT":         1,
		"TOKEN_KIND_STATIC":      2,
	}
)

func (x TokenKind) Enum() *TokenKind {
	p := new(TokenKind)
	*p = x
	return p
}

func (x TokenKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenKind) Descriptor() protoreflect.EnumDescriptor {
	return file_karlo_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (TokenKind) Type() protoreflect.EnumType {
	return &file_karlo_auth_v1_auth_proto_enumTypes[0]
}

func (x TokenKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenKind.Descriptor instead.
func (TokenKind) EnumDescriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// ProductAccess is one person's access to one product.
//
// A product absent from a user's access map is a product they cannot use at
// all, which is the common case rather than an edge one: a TMS driver has a tms
// entry and no fms entry.
type ProductAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant role, in that product's own vocabulary. TMS uses job personas
	// (shipper, transporter, driver); FMS uses privilege tiers (operator,
	// manager, admin). Neither has to accommodate the other.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Granted permission keys from the product's catalogue, e.g. "order.read".
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// grants_all marks an administrator role: everything the company is entitled
	// to, without enumerating it.
	//
	// It must cross the wire. A single-device session is validated through this
	// service on every request, so a principal rebuilt from this message IS the
	// principal the caller acts as — and without the flag an administrator
	// arrives with an empty permission list and is refused everywhere.
	GrantsAll bool `protobuf:"varint,4,opt,name=grants_all,json=grantsAll,proto3" json:"grants_all,omitempty"`
	// The COMPANY's entitlement for this product. The user's permissions can only
	// ever narrow it.
	Features      []string `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAccess) Reset() {
	*x = ProductAccess{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAccess) ProtoMessage() {}

func (x *ProductAccess) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAccess.ProtoReflect.Descriptor instead.
func (*ProductAccess) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ProductAccess) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ProductAccess) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ProductAccess) GetGrantsAll() bool {
	if x != nil {
		return x.GrantsAll
	}
	return false
}

func (x *ProductAccess) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type User struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone    string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	FullName string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// DEPRECATED: superseded by access. Retained so a caller mid-migration still
	// compiles; it carries the TMS role only.
	//
	// Deprecated: Marked as deprecated in karlo/auth/v1/auth.proto.
	Role string `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	// access holds this person's access per product, keyed by product ("tms",
	// "fms"). This is the authoritative field.
	Access map[string]*ProductAccess `protobuf:"bytes,20,rep,name=access,proto3" json:"access,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// is_platform_staff marks a Karlo employee, who administers across tenants
	// and bypasses company entitlement in both products. Product-neutral: a Karlo
	// employee is staff across both, not an administrator of one.
	IsPlatformStaff bool `protobuf:"varint,21,opt,name=is_platform_staff,json=isPlatformStaff,proto3" json:"is_platform_staff,omitempty"`
	// fms_tenant_id is the company's FMS-facing alias, carried so FMS reads its
	// bigint tenant id directly rather than translating the company UUID on every
	// request.
	FmsTenantId int64 `protobuf:"varint,22,opt,name=fms_tenant_id,json=fmsTenantId,proto3" json:"fms_tenant_id,omitempty"`
	// account_type is "mainAccount" for a company root account, "subAccount" for
	// a member created by a parent.
	AccountType string `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	ParentId    string `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CompanyId   string `protobuf:"bytes,9,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	IsSuspended bool   `protobuf:"varint,10,opt,name=is_suspended,json=isSuspended,proto3" json:"is_suspended,omitempty"`
	IsVerified  bool   `protobuf:"varint,11,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Deleted     bool   `protobuf:"varint,12,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Language    string `protobuf:"bytes,13,opt,name=language,proto3" json:"language,omitempty"`
	// permission is the module.action map, nested one level: module -> action -> bool.
	Permission    map[string]*PermissionModule `protobuf:"bytes,14,rep,name=permission,proto3" json:"permission,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp       `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp       `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

// Deprecated: Marked as deprecated in karlo/auth/v1/auth.proto.
func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetAccess() map[string]*ProductAccess {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *User) GetIsPlatformStaff() bool {
	if x != nil {
		return x.IsPlatformStaff
	}
	return false
}

func (x *User) GetFmsTenantId() int64 {
	if x != nil {
		return x.FmsTenantId
	}
	return 0
}

func (x *User) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *User) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *User) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *User) GetIsSuspended() bool {
	if x != nil {
		return x.IsSuspended
	}
	return false
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *User) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *User) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *User) GetPermission() map[string]*PermissionModule {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PermissionModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       map[string]bool        `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionModule) Reset() {
	*x = PermissionModule{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionModule) ProtoMessage() {}

func (x *PermissionModule) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionModule.ProtoReflect.Descriptor instead.
func (*PermissionModule) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionModule) GetActions() map[string]bool {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Company struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role      string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Npwp      string                 `protobuf:"bytes,4,opt,name=npwp,proto3" json:"npwp,omitempty"`
	Address   string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Settings  *CompanySettings       `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The short code that appears in agreement numbers:
	// AGR-<transporter>-<client>-000001. Derived from the name and editable.
	// Not unique — the sequence is what makes the number unique.
	Abbreviation  string `protobuf:"bytes,8,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Company) GetNpwp() string {
	if x != nil {
		return x.Npwp
	}
	return ""
}

func (x *Company) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Company) GetSettings() *CompanySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Company) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Company) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

// CompanySettings carries the per-company business toggles the legacy
// User.setting subdocument held. Business rules read these; they are served
// from here so there is a single owner.
type CompanySettings struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	CancelWithValidate               bool                   `protobuf:"varint,1,opt,name=cancel_with_validate,json=cancelWithValidate,proto3" json:"cancel_with_validate,omitempty"`
	FinishWithGeofencing             bool                   `protobuf:"varint,2,opt,name=finish_with_geofencing,json=finishWithGeofencing,proto3" json:"finish_with_geofencing,omitempty"`
	ActiveAgreementVerifiedOnly      bool                   `protobuf:"varint,3,opt,name=active_agreement_verified_only,json=activeAgreementVerifiedOnly,proto3" json:"active_agreement_verified_only,omitempty"`
	PpnPercentage                    float64                `protobuf:"fixed64,4,opt,name=ppn_percentage,json=ppnPercentage,proto3" json:"ppn_percentage,omitempty"`
	Pph23Percentage                  float64                `protobuf:"fixed64,5,opt,name=pph23_percentage,json=pph23Percentage,proto3" json:"pph23_percentage,omitempty"`
	UseStrictAgreement               bool                   `protobuf:"varint,6,opt,name=use_strict_agreement,json=useStrictAgreement,proto3" json:"use_strict_agreement,omitempty"`
	MaxDriverAvailableAfterOrderDone int32                  `protobuf:"varint,7,opt,name=max_driver_available_after_order_done,json=maxDriverAvailableAfterOrderDone,proto3" json:"max_driver_available_after_order_done,omitempty"`
	AccessTolls                      bool                   `protobuf:"varint,8,opt,name=access_tolls,json=accessTolls,proto3" json:"access_tolls,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CompanySettings) Reset() {
	*x = CompanySettings{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanySettings) ProtoMessage() {}

func (x *CompanySettings) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanySettings.ProtoReflect.Descriptor instead.
func (*CompanySettings) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CompanySettings) GetCancelWithValidate() bool {
	if x != nil {
		return x.CancelWithValidate
	}
	return false
}

func (x *CompanySettings) GetFinishWithGeofencing() bool {
	if x != nil {
		return x.FinishWithGeofencing
	}
	return false
}

func (x *CompanySettings) GetActiveAgreementVerifiedOnly() bool {
	if x != nil {
		return x.ActiveAgreementVerifiedOnly
	}
	return false
}

func (x *CompanySettings) GetPpnPercentage() float64 {
	if x != nil {
		return x.PpnPercentage
	}
	return 0
}

func (x *CompanySettings) GetPph23Percentage() float64 {
	if x != nil {
		return x.Pph23Percentage
	}
	return 0
}

func (x *CompanySettings) GetUseStrictAgreement() bool {
	if x != nil {
		return x.UseStrictAgreement
	}
	return false
}

func (x *CompanySettings) GetMaxDriverAvailableAfterOrderDone() int32 {
	if x != nil {
		return x.MaxDriverAvailableAfterOrderDone
	}
	return 0
}

func (x *CompanySettings) GetAccessTolls() bool {
	if x != nil {
		return x.AccessTolls
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User  *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// reason is set when valid is false, carrying the same message the legacy
	// middleware returned so existing clients keep their behaviour.
	Reason        string    `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Kind          TokenKind `protobuf:"varint,4,opt,name=kind,proto3,enum=karlo.auth.v1.TokenKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ValidateTokenResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateTokenResponse) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_TOKEN_KIND_UNSPECIFIED
}

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// include_deleted mirrors the legacy withDeleted query option.
	IncludeDeleted bool `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ids            []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetUsersRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetUsersRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetCompanyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyResponse) Reset() {
	*x = GetCompanyResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyResponse) ProtoMessage() {}

func (x *GetCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *GetCompanyResponse) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

type ListCompanyMembersRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CompanyId string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// roles narrows the result; empty means every role.
	Roles         []string  `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Query         *v1.Query `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompanyMembersRequest) Reset() {
	*x = ListCompanyMembersRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompanyMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompanyMembersRequest) ProtoMessage() {}

func (x *ListCompanyMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompanyMembersRequest.ProtoReflect.Descriptor instead.
func (*ListCompanyMembersRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ListCompanyMembersRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListCompanyMembersRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListCompanyMembersRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListCompanyMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompanyMembersResponse) Reset() {
	*x = ListCompanyMembersResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompanyMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompanyMembersResponse) ProtoMessage() {}

func (x *ListCompanyMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompanyMembersResponse.ProtoReflect.Descriptor instead.
func (*ListCompanyMembersResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ListCompanyMembersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListCompanyMembersResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type ResolveDeliveryTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDeliveryTargetsRequest) Reset() {
	*x = ResolveDeliveryTargetsRequest{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDeliveryTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDeliveryTargetsRequest) ProtoMessage() {}

func (x *ResolveDeliveryTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDeliveryTargetsRequest.ProtoReflect.Descriptor instead.
func (*ResolveDeliveryTargetsRequest) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveDeliveryTargetsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// DeliveryTarget is one user's reachable addresses.
type DeliveryTarget struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PushToken string                 `protobuf:"bytes,2,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	Email     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone     string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Language  string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	// extra_email_recipients mirrors User.emailRecipient: addresses copied on
	// document mail for this account.
	ExtraEmailRecipients []string `protobuf:"bytes,6,rep,name=extra_email_recipients,json=extraEmailRecipients,proto3" json:"extra_email_recipients,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeliveryTarget) Reset() {
	*x = DeliveryTarget{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryTarget) ProtoMessage() {}

func (x *DeliveryTarget) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryTarget.ProtoReflect.Descriptor instead.
func (*DeliveryTarget) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *DeliveryTarget) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeliveryTarget) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *DeliveryTarget) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeliveryTarget) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeliveryTarget) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeliveryTarget) GetExtraEmailRecipients() []string {
	if x != nil {
		return x.ExtraEmailRecipients
	}
	return nil
}

type ResolveDeliveryTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*DeliveryTarget      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDeliveryTargetsResponse) Reset() {
	*x = ResolveDeliveryTargetsResponse{}
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDeliveryTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDeliveryTargetsResponse) ProtoMessage() {}

func (x *ResolveDeliveryTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDeliveryTargetsResponse.ProtoReflect.Descriptor instead.
func (*ResolveDeliveryTargetsResponse) Descriptor() ([]byte, []int) {
	return file_karlo_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveDeliveryTargetsResponse) GetTargets() []*DeliveryTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_karlo_auth_v1_auth_proto protoreflect.FileDescriptor

const file_karlo_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18karlo/auth/v1/auth.proto\x12\rkarlo.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ckarlo/common/v1/common.proto\"\x80\x01\n" +
	"\rProductAccess\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"grants_all\x18\x04 \x01(\bR\tgrantsAll\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"\xe9\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x16\n" +
	"\x04role\x18\x06 \x01(\tB\x02\x18\x01R\x04role\x127\n" +
	"\x06access\x18\x14 \x03(\v2\x1f.karlo.auth.v1.User.AccessEntryR\x06access\x12*\n" +
	"\x11is_platform_staff\x18\x15 \x01(\bR\x0fisPlatformStaff\x12\"\n" +
	"\rfms_tenant_id\x18\x16 \x01(\x03R\vfmsTenantId\x12!\n" +
	"\faccount_type\x18\a \x01(\tR\vaccountType\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"company_id\x18\t \x01(\tR\tcompanyId\x12!\n" +
	"\fis_suspended\x18\n" +
	" \x01(\bR\visSuspended\x12\x1f\n" +
	"\vis_verified\x18\v \x01(\bR\n" +
	"isVerified\x12\x18\n" +
	"\adeleted\x18\f \x01(\bR\adeleted\x12\x1a\n" +
	"\blanguage\x18\r \x01(\tR\blanguage\x12C\n" +
	"\n" +
	"permission\x18\x0e \x03(\v2#.karlo.auth.v1.User.PermissionEntryR\n" +
	"permission\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aW\n" +
	"\vAccessEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.karlo.auth.v1.ProductAccessR\x05value:\x028\x01\x1a^\n" +
	"\x0fPermissionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.karlo.auth.v1.PermissionModuleR\x05value:\x028\x01\"\x96\x01\n" +
	"\x10PermissionModule\x12F\n" +
	"\aactions\x18\x01 \x03(\v2,.karlo.auth.v1.PermissionModule.ActionsEntryR\aactions\x1a:\n" +
	"\fActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x8a\x02\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04npwp\x18\x04 \x01(\tR\x04npwp\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12:\n" +
	"\bsettings\x18\x06 \x01(\v2\x1e.karlo.auth.v1.CompanySettingsR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\"\n" +
	"\fabbreviation\x18\b \x01(\tR\fabbreviation\"\xb6\x03\n" +
	"\x0fCompanySettings\x120\n" +
	"\x14cancel_with_validate\x18\x01 \x01(\bR\x12cancelWithValidate\x124\n" +
	"\x16finish_with_geofencing\x18\x02 \x01(\bR\x14finishWithGeofencing\x12C\n" +
	"\x1eactive_agreement_verified_only\x18\x03 \x01(\bR\x1bactiveAgreementVerifiedOnly\x12%\n" +
	"\x0eppn_percentage\x18\x04 \x01(\x01R\rppnPercentage\x12)\n" +
	"\x10pph23_percentage\x18\x05 \x01(\x01R\x0fpph23Percentage\x120\n" +
	"\x14use_strict_agreement\x18\x06 \x01(\bR\x12useStrictAgreement\x12O\n" +
	"%max_driver_available_after_order_done\x18\a \x01(\x05R maxDriverAvailableAfterOrderDone\x12!\n" +
	"\faccess_tolls\x18\b \x01(\bR\vaccessTolls\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x9c\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12'\n" +
	"\x04user\x18\x02 \x01(\v2\x13.karlo.auth.v1.UserR\x04user\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12,\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x18.karlo.auth.v1.TokenKindR\x04kind\"I\n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\":\n" +
	"\x0fGetUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.karlo.auth.v1.UserR\x04user\"L\n" +
	"\x0fGetUsersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\"=\n" +
	"\x10GetUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.karlo.auth.v1.UserR\x05users\"a\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"3\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"#\n" +
	"\x11GetCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x12GetCompanyResponse\x120\n" +
	"\acompany\x18\x01 \x01(\v2\x16.karlo.auth.v1.CompanyR\acompany\"~\n" +
	"\x19ListCompanyMembersRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12,\n" +
	"\x05query\x18\x03 \x01(\v2\x16.karlo.common.v1.QueryR\x05query\"\x7f\n" +
	"\x1aListCompanyMembersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.karlo.auth.v1.UserR\x05users\x126\n" +
	"\tpage_info\x18\x02 \x01(\v2\x19.karlo.common.v1.PageInfoR\bpageInfo\":\n" +
	"\x1dResolveDeliveryTargetsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xc6\x01\n" +
	"\x0eDeliveryTarget\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"push_token\x18\x02 \x01(\tR\tpushToken\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x124\n" +
	"\x16extra_email_recipients\x18\x06 \x03(\tR\x14extraEmailRecipients\"Y\n" +
	"\x1eResolveDeliveryTargetsResponse\x127\n" +
	"\atargets\x18\x01 \x03(\v2\x1d.karlo.auth.v1.DeliveryTargetR\atargets*R\n" +
	"\tTokenKind\x12\x1a\n" +
	"\x16TOKEN_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTOKEN_KIND_JWT\x10\x01\x12\x15\n" +
	"\x11TOKEN_KIND_STATIC\x10\x022\x97\x05\n" +
	"\vAuthService\x12Z\n" +
	"\rValidateToken\x12#.karlo.auth.v1.ValidateTokenRequest\x1a$.karlo.auth.v1.ValidateTokenResponse\x12H\n" +
	"\aGetUser\x12\x1d.karlo.auth.v1.GetUserRequest\x1a\x1e.karlo.auth.v1.GetUserResponse\x12K\n" +
	"\bGetUsers\x12\x1e.karlo.auth.v1.GetUsersRequest\x1a\x1f.karlo.auth.v1.GetUsersResponse\x12`\n" +
	"\x0fCheckPermission\x12%.karlo.auth.v1.CheckPermissionRequest\x1a&.karlo.auth.v1.CheckPermissionResponse\x12Q\n" +
	"\n" +
	"GetCompany\x12 .karlo.auth.v1.GetCompanyRequest\x1a!.karlo.auth.v1.GetCompanyResponse\x12i\n" +
	"\x12ListCompanyMembers\x12(.karlo.auth.v1.ListCompanyMembersRequest\x1a).karlo.auth.v1.ListCompanyMembersResponse\x12u\n" +
	"\x16ResolveDeliveryTargets\x12,.karlo.auth.v1.ResolveDeliveryTargetsRequest\x1a-.karlo.auth.v1.ResolveDeliveryTargetsResponseB\xcb\x01\n" +
	"\x11com.karlo.auth.v1B\tAuthProtoP\x01ZUgithub.com/karlo/notification-service/internal/platform/genproto/karlo/auth/v1;authv1\xa2\x02\x03KAX\xaa\x02\rKarlo.Auth.V1\xca\x02\rKarlo\\Auth\\V1\xe2\x02\x19Karlo\\Auth\\V1\\GPBMetadata\xea\x02\x0fKarlo::Auth::V1b\x06proto3"

var (
	file_karlo_auth_v1_auth_proto_rawDescOnce sync.Once
	file_karlo_auth_v1_auth_proto_rawDescData []byte
)

func file_karlo_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_karlo_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_karlo_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_karlo_auth_v1_auth_proto_rawDesc), len(file_karlo_auth_v1_auth_proto_rawDesc)))
	})
	return file_karlo_auth_v1_auth_proto_rawDescData
}

var file_karlo_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_karlo_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_karlo_auth_v1_auth_proto_goTypes = []any{
	(TokenKind)(0),                         // 0: karlo.auth.v1.TokenKind
	(*ProductAccess)(nil),                  // 1: karlo.auth.v1.ProductAccess
	(*User)(nil),                           // 2: karlo.auth.v1.User
	(*PermissionModule)(nil),               // 3: karlo.auth.v1.PermissionModule
	(*Company)(nil),                        // 4: karlo.auth.v1.Company
	(*CompanySettings)(nil),                // 5: karlo.auth.v1.CompanySettings
	(*ValidateTokenRequest)(nil),           // 6: karlo.auth.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),          // 7: karlo.auth.v1.ValidateTokenResponse
	(*GetUserRequest)(nil),                 // 8: karlo.auth.v1.GetUserRequest
	(*GetUserResponse)(nil),                // 9: karlo.auth.v1.GetUserResponse
	(*GetUsersRequest)(nil),                // 10: karlo.auth.v1.GetUsersRequest
	(*GetUsersResponse)(nil),               // 11: karlo.auth.v1.GetUsersResponse
	(*CheckPermissionRequest)(nil),         // 12: karlo.auth.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),        // 13: karlo.auth.v1.CheckPermissionResponse
	(*GetCompanyRequest)(nil),              // 14: karlo.auth.v1.GetCompanyRequest
	(*GetCompanyResponse)(nil),             // 15: karlo.auth.v1.GetCompanyResponse
	(*ListCompanyMembersRequest)(nil),      // 16: karlo.auth.v1.ListCompanyMembersRequest
	(*ListCompanyMembersResponse)(nil),     // 17: karlo.auth.v1.ListCompanyMembersResponse
	(*ResolveDeliveryTargetsRequest)(nil),  // 18: karlo.auth.v1.ResolveDeliveryTargetsRequest
	(*DeliveryTarget)(nil),                 // 19: karlo.auth.v1.DeliveryTarget
	(*ResolveDeliveryTargetsResponse)(nil), // 20: karlo.auth.v1.ResolveDeliveryTargetsResponse
	nil,                                    // 21: karlo.auth.v1.User.AccessEntry
	nil,                                    // 22: karlo.auth.v1.User.PermissionEntry
	nil,                                    // 23: karlo.auth.v1.PermissionModule.ActionsEntry
	(*timestamppb.Timestamp)(nil),          // 24: google.protobuf.Timestamp
	(*v1.Query)(nil),                       // 25: karlo.common.v1.Query
	(*v1.PageInfo)(nil),                    // 26: karlo.common.v1.PageInfo
}
var file_karlo_auth_v1_auth_proto_depIdxs = []int32{
	21, // 0: karlo.auth.v1.User.access:type_name -> karlo.auth.v1.User.AccessEntry
	22, // 1: karlo.auth.v1.User.permission:type_name -> karlo.auth.v1.User.PermissionEntry
	24, // 2: karlo.auth.v1.User.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: karlo.auth.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	23, // 4: karlo.auth.v1.PermissionModule.actions:type_name -> karlo.auth.v1.PermissionModule.ActionsEntry
	5,  // 5: karlo.auth.v1.Company.settings:type_name -> karlo.auth.v1.CompanySettings
	24, // 6: karlo.auth.v1.Company.created_at:type_name -> google.protobuf.Timestamp
	2,  // 7: karlo.auth.v1.ValidateTokenResponse.user:type_name -> karlo.auth.v1.User
	0,  // 8: karlo.auth.v1.ValidateTokenResponse.kind:type_name -> karlo.auth.v1.TokenKind
	2,  // 9: karlo.auth.v1.GetUserResponse.user:type_name -> karlo.auth.v1.User
	2,  // 10: karlo.auth.v1.GetUsersResponse.users:type_name -> karlo.auth.v1.User
	4,  // 11: karlo.auth.v1.GetCompanyResponse.company:type_name -> karlo.auth.v1.Company
	25, // 12: karlo.auth.v1.ListCompanyMembersRequest.query:type_name -> karlo.common.v1.Query
	2,  // 13: karlo.auth.v1.ListCompanyMembersResponse.users:type_name -> karlo.auth.v1.User
	26, // 14: karlo.auth.v1.ListCompanyMembersResponse.page_info:type_name -> karlo.common.v1.PageInfo
	19, // 15: karlo.auth.v1.ResolveDeliveryTargetsResponse.targets:type_name -> karlo.auth.v1.DeliveryTarget
	1,  // 16: karlo.auth.v1.User.AccessEntry.value:type_name -> karlo.auth.v1.ProductAccess
	3,  // 17: karlo.auth.v1.User.PermissionEntry.value:type_name -> karlo.auth.v1.PermissionModule
	6,  // 18: karlo.auth.v1.AuthService.ValidateToken:input_type -> karlo.auth.v1.ValidateTokenRequest
	8,  // 19: karlo.auth.v1.AuthService.GetUser:input_type -> karlo.auth.v1.GetUserRequest
	10, // 20: karlo.auth.v1.AuthService.GetUsers:input_type -> karlo.auth.v1.GetUsersRequest
	12, // 21: karlo.auth.v1.AuthService.CheckPermission:input_type -> karlo.auth.v1.CheckPermissionRequest
	14, // 22: karlo.auth.v1.AuthService.GetCompany:input_type -> karlo.auth.v1.GetCompanyRequest
	16, // 23: karlo.auth.v1.AuthService.ListCompanyMembers:input_type -> karlo.auth.v1.ListCompanyMembersRequest
	18, // 24: karlo.auth.v1.AuthService.ResolveDeliveryTargets:input_type -> karlo.auth.v1.ResolveDeliveryTargetsRequest
	7,  // 25: karlo.auth.v1.AuthService.ValidateToken:output_type -> karlo.auth.v1.ValidateTokenResponse
	9,  // 26: karlo.auth.v1.AuthService.GetUser:output_type -> karlo.auth.v1.GetUserResponse
	11, // 27: karlo.auth.v1.AuthService.GetUsers:output_type -> karlo.auth.v1.GetUsersResponse
	13, // 28: karlo.auth.v1.AuthService.CheckPermission:output_type -> karlo.auth.v1.CheckPermissionResponse
	15, // 29: karlo.auth.v1.AuthService.GetCompany:output_type -> karlo.auth.v1.GetCompanyResponse
	17, // 30: karlo.auth.v1.AuthService.ListCompanyMembers:output_type -> karlo.auth.v1.ListCompanyMembersResponse
	20, // 31: karlo.auth.v1.AuthService.ResolveDeliveryTargets:output_type -> karlo.auth.v1.ResolveDeliveryTargetsResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_karlo_auth_v1_auth_proto_init() }
func file_karlo_auth_v1_auth_proto_init() {
	if File_karlo_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_karlo_auth_v1_auth_proto_rawDesc), len(file_karlo_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_karlo_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_karlo_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_karlo_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_karlo_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_karlo_auth_v1_auth_proto = out.File
	file_karlo_auth_v1_auth_proto_goTypes = nil
	file_karlo_auth_v1_auth_proto_depIdxs = nil
}
