// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: karlo/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_OPERATOR_EQ          Operator = 1
	Operator_OPERATOR_NEQ         Operator = 2
	Operator_OPERATOR_LIKE        Operator = 3
	Operator_OPERATOR_IN          Operator = 4
	Operator_OPERATOR_GT          Operator = 5
	Operator_OPERATOR_GTE         Operator = 6
	Operator_OPERATOR_LT          Operator = 7
	Operator_OPERATOR_LTE         Operator = 8
	Operator_OPERATOR_BETWEEN     Operator = 9
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "OPERATOR_EQ",
		2: "OPERATOR_NEQ",
		3: "OPERATOR_LIKE",
		4: "OPERATOR_IN",
		5: "OPERATOR_GT",
		6: "OPERATOR_GTE",
		7: "OPERATOR_LT",
		8: "OPERATOR_LTE",
		9: "OPERATOR_BETWEEN",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"OPERATOR_EQ":          1,
		"OPERATOR_NEQ":         2,
		"OPERATOR_LIKE":        3,
		"OPERATOR_IN":          4,
		"OPERATOR_GT":          5,
		"OPERATOR_GTE":         6,
		"OPERATOR_LT":          7,
		"OPERATOR_LTE":         8,
		"OPERATOR_BETWEEN":     9,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_karlo_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_karlo_common_v1_common_proto_enumTypes[0]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_karlo_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// Page describes a request for one page of a listing.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_karlo_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_karlo_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Page) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// PageInfo describes the pagination state of a listing response.
type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalRows     int64                  `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_karlo_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_karlo_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInfo) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *PageInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Filter mirrors the {id, value} filter objects the legacy REST API accepts in
// its `filtered` query parameter, so the same client filters survive the split.
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operator      Operator               `protobuf:"varint,3,opt,name=operator,proto3,enum=karlo.common.v1.Operator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_karlo_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_karlo_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Filter) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_OPERATOR_UNSPECIFIED
}

// Sort mirrors the legacy `sorted` query parameter.
type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_karlo_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_karlo_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Sort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sort) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// Query bundles the three listing parameters every service accepts.
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Filtered      []*Filter              `protobuf:"bytes,2,rep,name=filtered,proto3" json:"filtered,omitempty"`
	Sorted        []*Sort                `protobuf:"bytes,3,rep,name=sorted,proto3" json:"sorted,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_karlo_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_karlo_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_karlo_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Query) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *Query) GetFiltered() []*Filter {
	if x != nil {
		return x.Filtered
	}
	return nil
}

func (x *Query) GetSorted() []*Sort {
	if x != nil {
		return x.Sorted
	}
	return nil
}

func (x *Query) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_karlo_common_v1_common_proto protoreflect.FileDescriptor

const file_karlo_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1ckarlo/common/v1/common.proto\x12\x0fkarlo.common.v1\"7\n" +
	"\x04Page\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"{\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x03 \x01(\x03R\ttotalRows\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"e\n" +
	"\x06Filter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x125\n" +
	"\boperator\x18\x03 \x01(\x0e2\x19.karlo.common.v1.OperatorR\boperator\"*\n" +
	"\x04Sort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"\xae\x01\n" +
	"\x05Query\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.karlo.common.v1.PageR\x04page\x123\n" +
	"\bfiltered\x18\x02 \x03(\v2\x17.karlo.common.v1.FilterR\bfiltered\x12-\n" +
	"\x06sorted\x18\x03 \x03(\v2\x15.karlo.common.v1.SortR\x06sorted\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search*\xc7\x01\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATOR_EQ\x10\x01\x12\x10\n" +
	"\fOPERATOR_NEQ\x10\x02\x12\x11\n" +
	"\rOPERATOR_LIKE\x10\x03\x12\x0f\n" +
	"\vOPERATOR_IN\x10\x04\x12\x0f\n" +
	"\vOPERATOR_GT\x10\x05\x12\x10\n" +
	"\fOPERATOR_GTE\x10\x06\x12\x0f\n" +
	"\vOPERATOR_LT\x10\a\x12\x10\n" +
	"\fOPERATOR_LTE\x10\b\x12\x14\n" +
	"\x10OPERATOR_BETWEEN\x10\tB\xc4\x01\n" +
	"\x13com.karlo.common.v1B\vCommonProtoP\x01ZBgithub.com/karlo/notification-service/internal/platform/genproto/karlo/common/v1;commonv1\xa2\x02\x03KCX\xaa\x02\x0fKarlo.Common.V1\xca\x02\x0fKarlo\\Common\\V1\xe2\x02\x1bKarlo\\Common\\V1\\GPBMetadata\xea\x02\x11Karlo::Common::V1b\x06proto3"

var (
	file_karlo_common_v1_common_proto_rawDescOnce sync.Once
	file_karlo_common_v1_common_proto_rawDescData []byte
)

func file_karlo_common_v1_common_proto_rawDescGZIP() []byte {
	file_karlo_common_v1_common_proto_rawDescOnce.Do(func() {
		file_karlo_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_karlo_common_v1_common_proto_rawDesc), len(file_karlo_common_v1_common_proto_rawDesc)))
	})
	return file_karlo_common_v1_common_proto_rawDescData
}

var file_karlo_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_karlo_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_karlo_common_v1_common_proto_goTypes = []any{
	(Operator)(0),    // 0: karlo.common.v1.Operator
	(*Page)(nil),     // 1: karlo.common.v1.Page
	(*PageInfo)(nil), // 2: karlo.common.v1.PageInfo
	(*Filter)(nil),   // 3: karlo.common.v1.Filter
	(*Sort)(nil),     // 4: karlo.common.v1.Sort
	(*Query)(nil),    // 5: karlo.common.v1.Query
}
var file_karlo_common_v1_common_proto_depIdxs = []int32{
	0, // 0: karlo.common.v1.Filter.operator:type_name -> karlo.common.v1.Operator
	1, // 1: karlo.common.v1.Query.page:type_name -> karlo.common.v1.Page
	3, // 2: karlo.common.v1.Query.filtered:type_name -> karlo.common.v1.Filter
	4, // 3: karlo.common.v1.Query.sorted:type_name -> karlo.common.v1.Sort
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_karlo_common_v1_common_proto_init() }
func file_karlo_common_v1_common_proto_init() {
	if File_karlo_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_karlo_common_v1_common_proto_rawDesc), len(file_karlo_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_karlo_common_v1_common_proto_goTypes,
		DependencyIndexes: file_karlo_common_v1_common_proto_depIdxs,
		EnumInfos:         file_karlo_common_v1_common_proto_enumTypes,
		MessageInfos:      file_karlo_common_v1_common_proto_msgTypes,
	}.Build()
	File_karlo_common_v1_common_proto = out.File
	file_karlo_common_v1_common_proto_goTypes = nil
	file_karlo_common_v1_common_proto_depIdxs = nil
}
